<?php

return [
    [
        'id' => 3,
        'name' => 'Interval Extensiv',
        'config' => [
            'settings' => [
                'heartRate',
                'duration',
                'heartRateZone',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Interval',
                'default' => 7,
            ],
            'distance' => null,
            'duration' => [
                'unit' => 'minutes',
                'default' => 1,
                'applyPer' => 'session',
            ],
            'heartRate' => [
                'default' => '140',
                'applyPer' => 'session',
            ],
            'heartRateZone' => [
                'default' => '3',
                'applyPer' => 'session',
            ],
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
    ],
    [
        'id' => 4,
        'name' => 'Interval Watt Bike',
        'config' => [
            'settings' => [
                'watts',
                'duration',
                'heartRateZone',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Interval',
                'default' => 5,
            ],
            'distance' => null,
            'duration' => [
                'unit' => 'seconds',
                'default' => 60,
                'applyPer' => 'session',
            ],
            'heartRate' => null,
            'heartRateZone' => [
                'default' => '3',
                'applyPer' => 'session',
            ],
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => [
                'default' => 60,
                'applyPer' => 'week',
            ],
            'tempo' => [
                'default' => '3010',
                'applyPer' => 'week',
            ],
            'watts' => [
                'default' => 100,
                'applyPer' => 'session',
            ],
            'weight' => [
                'mode' => 'manual',
                'oneRepMaxModifier' => 100,
                'default' => 5,
                'applyPer' => 'session',
            ],
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
    ],
    [
        'id' => 8,
        'name' => 'Lisa am Morgen ',
        'config' => [
            'settings' => [
                'reps',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 5,
            ],
            'distance' => null,
            'duration' => [
                'unit' => 'seconds',
                'default' => 60,
                'applyPer' => 'session',
            ],
            'heartRate' => [
                'default' => '140',
                'applyPer' => 'session',
            ],
            'heartRateZone' => [
                'default' => '3',
                'applyPer' => 'session',
            ],
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
    ],
    [
        'id' => 1,
        'name' => 'Strength (Automatic)',
        'config' => [
            'settings' => [
                'reps',
                'weight',
                'tempo',
                'rest',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'odd',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 4,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'automatic',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => [
                'default' => 60,
                'applyPer' => 'week',
            ],
            'tempo' => [
                'default' => '3010',
                'applyPer' => 'week',
            ],
            'watts' => null,
            'weight' => [
                'mode' => 'automatic',
                'oneRepMaxModifier' => 100,
                'default' => 5,
                'applyPer' => 'session',
            ],
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
    ],
    [
        'id' => 2,
        'name' => 'Strength (Manual)',
        'config' => [
            'settings' => [
                'reps',
                'weight',
                'tempo',
                'rest',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 4,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => [
                'default' => 60,
                'applyPer' => 'week',
            ],
            'tempo' => [
                'default' => '3010',
                'applyPer' => 'week',
            ],
            'watts' => null,
            'weight' => [
                'mode' => 'manual',
                'oneRepMaxModifier' => 100,
                'default' => 5,
                'applyPer' => 'session',
            ],
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
    ],
];
