<?php

return [
    [
        'id' => 4,
        'name' => 'ATG Split Squat',
        'category_id' => 323,
        'template_id' => 2,
        'video_url' => 'https://www.youtube.com/shorts/LHX34TpJxbQ',
        'instructions' => 'Knie muss über Fussspitze kommen ',
        'config' => [
            'settings' => [
                'reps',
                'weight',
                'tempo',
                'rest',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 4,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => [
                'default' => 60,
                'applyPer' => 'week',
            ],
            'tempo' => [
                'default' => '3010',
                'applyPer' => 'week',
            ],
            'watts' => null,
            'weight' => [
                'mode' => 'manual',
                'oneRepMaxModifier' => 100,
                'default' => 5,
                'applyPer' => 'session',
            ],
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'id' => 82,
                'sort' => 0,
            ],
            [
                'id' => 357,
                'sort' => 0,
            ],
        ],
    ],
    [
        'id' => 25,
        'name' => 'ATG Split Squat',
        'category_id' => 323,
        'template_id' => 2,
        'video_url' => 'https://www.youtube.com/watch?v=X97CYfHWSF4',
        'instructions' => 'Back leg straightened if possible',
        'config' => [
            'settings' => [
                'reps',
                'weight',
                'tempo',
                'rest',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 4,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => [
                'default' => 60,
                'applyPer' => 'week',
            ],
            'tempo' => [
                'default' => '3010',
                'applyPer' => 'week',
            ],
            'watts' => null,
            'weight' => [
                'mode' => 'manual',
                'oneRepMaxModifier' => 100,
                'default' => 5,
                'applyPer' => 'session',
            ],
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'id' => 82,
                'sort' => 0,
            ],
            [
                'id' => 223,
                'sort' => 0,
            ],
        ],
    ],
    [
        'id' => 9,
        'name' => 'Back Squat',
        'category_id' => null,
        'template_id' => 1,
        'video_url' => 'https://www.youtube.com/watch?v=CPgCggIyn-g',
        'instructions' => 'So lange runter bis rücken gerade ist',
        'config' => [
            'settings' => [
                'reps',
                'weight',
                'tempo',
                'rest',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'odd',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 4,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'automatic',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => [
                'default' => 60,
                'applyPer' => 'week',
            ],
            'tempo' => [
                'default' => '3010',
                'applyPer' => 'week',
            ],
            'watts' => null,
            'weight' => [
                'mode' => 'automatic',
                'oneRepMaxModifier' => 100,
                'default' => 5,
                'applyPer' => 'session',
            ],
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'id' => 104,
                'sort' => 0,
            ],
        ],
    ],
    [
        'id' => 7,
        'name' => 'Chin-Up',
        'category_id' => null,
        'template_id' => null,
        'video_url' => 'https://youtu.be/jWG018GIUjY',
        'instructions' => 'Gleichmässig runter',
        'config' => [
            'settings' => [
                'reps',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 5,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'id' => 91,
                'sort' => 0,
            ],
            [
                'id' => 121,
                'sort' => 0,
            ],
        ],
    ],
    [
        'id' => 13,
        'name' => 'core plank + side plank',
        'category_id' => null,
        'template_id' => null,
        'video_url' => 'https://www.youtube.com/shorts/tJwHo9kg5GI',
        'instructions' => 'Brustkasten raus!',
        'config' => [
            'settings' => [
                'reps',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 7,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [],
    ],
    [
        'id' => 10,
        'name' => 'Dip',
        'category_id' => null,
        'template_id' => null,
        'video_url' => 'https://youtu.be/dG99wTA7d2U',
        'instructions' => 'Ellenbogen drin behalten',
        'config' => [
            'settings' => [
                'reps',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 5,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [],
    ],
    [
        'id' => 5,
        'name' => 'Front Squat ',
        'category_id' => null,
        'template_id' => 1,
        'video_url' => 'https://www.youtube.com/shorts/iVtH8lZATdQ',
        'instructions' => 'Ellenbogen hochnehmen die ganze Zeit',
        'config' => [
            'settings' => [
                'reps',
                'weight',
                'tempo',
                'rest',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'odd',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 4,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'automatic',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => [
                'default' => 60,
                'applyPer' => 'week',
            ],
            'tempo' => [
                'default' => '3010',
                'applyPer' => 'week',
            ],
            'watts' => null,
            'weight' => [
                'mode' => 'automatic',
                'oneRepMaxModifier' => 100,
                'default' => 5,
                'applyPer' => 'session',
            ],
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'id' => 104,
                'sort' => 0,
            ],
            [
                'id' => 81,
                'sort' => 0,
            ],
        ],
    ],
    [
        'id' => 24,
        'name' => 'Hütchensprint li/re',
        'category_id' => 326,
        'template_id' => null,
        'video_url' => null,
        'instructions' => null,
        'config' => [
            'settings' => [
                'reps',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 5,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'id' => 328,
                'sort' => 0,
            ],
            [
                'id' => 329,
                'sort' => 0,
            ],
            [
                'id' => 330,
                'sort' => 0,
            ],
        ],
    ],
    [
        'id' => 26,
        'name' => 'Interval Bike Extensiv Indoor',
        'category_id' => 359,
        'template_id' => 3,
        'video_url' => 'https://www.youtube.com/shorts/jN3HeMMvB5o',
        'instructions' => '',
        'config' => [
            'settings' => [
                'heartRate',
                'duration',
                'heartRateZone',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Interval',
                'default' => 7,
            ],
            'distance' => null,
            'duration' => [
                'unit' => 'minutes',
                'default' => 1,
                'applyPer' => 'session',
            ],
            'heartRate' => [
                'default' => '140',
                'applyPer' => 'session',
            ],
            'heartRateZone' => [
                'default' => '3',
                'applyPer' => 'session',
            ],
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'id' => 361,
                'sort' => 0,
            ],
            [
                'id' => 360,
                'sort' => 0,
            ],
        ],
    ],
    [
        'id' => 27,
        'name' => 'Interval Bike Extensiv Outdoor',
        'category_id' => 359,
        'template_id' => 3,
        'video_url' => null,
        'instructions' => null,
        'config' => [
            'settings' => [
                'heartRate',
                'duration',
                'heartRateZone',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Interval',
                'default' => 7,
            ],
            'distance' => null,
            'duration' => [
                'unit' => 'minutes',
                'default' => 1,
                'applyPer' => 'session',
            ],
            'heartRate' => [
                'default' => '140',
                'applyPer' => 'session',
            ],
            'heartRateZone' => [
                'default' => '3',
                'applyPer' => 'session',
            ],
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'id' => 366,
                'sort' => 0,
            ],
            [
                'id' => 329,
                'sort' => 0,
            ],
        ],
    ],
    [
        'id' => 29,
        'name' => 'Interval Jogging Extensiv Indoor',
        'category_id' => 359,
        'template_id' => 3,
        'video_url' => 'https://www.youtube.com/shorts/sMXvl_iOW88',
        'instructions' => null,
        'config' => [
            'settings' => [
                'heartRate',
                'duration',
                'heartRateZone',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Interval',
                'default' => 7,
            ],
            'distance' => null,
            'duration' => [
                'unit' => 'minutes',
                'default' => 1,
                'applyPer' => 'session',
            ],
            'heartRate' => [
                'default' => '140',
                'applyPer' => 'session',
            ],
            'heartRateZone' => [
                'default' => '3',
                'applyPer' => 'session',
            ],
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'id' => 367,
                'sort' => 0,
            ],
            [
                'id' => 360,
                'sort' => 0,
            ],
        ],
    ],
    [
        'id' => 28,
        'name' => 'Interval Jogging Extensiv Outdoor',
        'category_id' => 359,
        'template_id' => 3,
        'video_url' => null,
        'instructions' => null,
        'config' => [
            'settings' => [
                'heartRate',
                'duration',
                'heartRateZone',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Interval',
                'default' => 7,
            ],
            'distance' => null,
            'duration' => [
                'unit' => 'minutes',
                'default' => 1,
                'applyPer' => 'session',
            ],
            'heartRate' => [
                'default' => '140',
                'applyPer' => 'session',
            ],
            'heartRateZone' => [
                'default' => '3',
                'applyPer' => 'session',
            ],
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'id' => 329,
                'sort' => 0,
            ],
        ],
    ],
    [
        'id' => 30,
        'name' => 'kNIEBEUGE HINTEN AUF BRETT LH',
        'category_id' => 323,
        'template_id' => 1,
        'video_url' => null,
        'instructions' => null,
        'config' => [
            'settings' => [
                'reps',
                'weight',
                'tempo',
                'rest',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'odd',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 4,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'automatic',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => [
                'default' => 60,
                'applyPer' => 'week',
            ],
            'tempo' => [
                'default' => '3010',
                'applyPer' => 'week',
            ],
            'watts' => null,
            'weight' => [
                'mode' => 'automatic',
                'oneRepMaxModifier' => 100,
                'default' => 5,
                'applyPer' => 'session',
            ],
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [],
    ],
    [
        'id' => 16,
        'name' => 'Koordination Ragettli Parcour',
        'category_id' => null,
        'template_id' => null,
        'video_url' => 'https://www.youtube.com/watch?v=AfD736-n0e8',
        'instructions' => 'Nicht verletzten',
        'config' => [
            'settings' => [
                'reps',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 5,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [],
    ],
    [
        'id' => 6,
        'name' => 'Lastheben ',
        'category_id' => null,
        'template_id' => 1,
        'video_url' => 'https://www.youtube.com/watch?v=CPgCggIyn-g',
        'instructions' => 'Stange immer am Körper lassen',
        'config' => [
            'settings' => [
                'reps',
                'weight',
                'tempo',
                'rest',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'odd',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 4,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'automatic',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => [
                'default' => 60,
                'applyPer' => 'week',
            ],
            'tempo' => [
                'default' => '3010',
                'applyPer' => 'week',
            ],
            'watts' => null,
            'weight' => [
                'mode' => 'automatic',
                'oneRepMaxModifier' => 100,
                'default' => 5,
                'applyPer' => 'session',
            ],
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'id' => 104,
                'sort' => 0,
            ],
        ],
    ],
    [
        'id' => 31,
        'name' => 'Lastheben',
        'category_id' => 323,
        'template_id' => 2,
        'video_url' => null,
        'instructions' => null,
        'config' => [
            'settings' => [
                'reps',
                'weight',
                'tempo',
                'rest',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 4,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => [
                'default' => 60,
                'applyPer' => 'week',
            ],
            'tempo' => [
                'default' => '3010',
                'applyPer' => 'week',
            ],
            'watts' => null,
            'weight' => [
                'mode' => 'manual',
                'oneRepMaxModifier' => 100,
                'default' => 5,
                'applyPer' => 'session',
            ],
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'id' => 81,
                'sort' => 0,
            ],
            [
                'id' => 104,
                'sort' => 0,
            ],
        ],
    ],
    [
        'id' => 8,
        'name' => 'Push Press',
        'category_id' => null,
        'template_id' => null,
        'video_url' => 'https://youtu.be/isXQmhH6AEM',
        'instructions' => 'Sehr Explosiv Arbieten',
        'config' => [
            'settings' => [
                'reps',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 5,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'id' => 81,
                'sort' => 0,
            ],
            [
                'id' => 87,
                'sort' => 0,
            ],
            [
                'id' => 109,
                'sort' => 0,
            ],
        ],
    ],
    [
        'id' => 23,
        'name' => 'Skischuh Squatjump',
        'category_id' => null,
        'template_id' => 2,
        'video_url' => null,
        'instructions' => 'Hands on hip, Executive a Jump 90 degrees max and Full length with skiboots',
        'config' => [
            'settings' => [
                'reps',
                'weight',
                'tempo',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 4,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => '4',
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => [
                'default' => 60,
                'applyPer' => 'week',
            ],
            'tempo' => [
                'default' => '30x0',
                'applyPer' => 'week',
            ],
            'watts' => [
                'default' => 100,
                'applyPer' => 'session',
            ],
            'weight' => [
                'mode' => 'manual',
                'oneRepMaxModifier' => 100,
                'default' => 10,
                'applyPer' => 'session',
            ],
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'id' => 308,
                'sort' => 0,
            ],
            [
                'id' => 310,
                'sort' => 0,
            ],
        ],
    ],
    [
        'id' => 11,
        'name' => 'Step up ',
        'category_id' => null,
        'template_id' => 2,
        'video_url' => 'https://www.youtube.com/shorts/r-wWtYEzYIw',
        'instructions' => 'Ohne Schwung',
        'config' => [
            'settings' => [
                'reps',
                'weight',
                'tempo',
                'rest',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 4,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => [
                'default' => 60,
                'applyPer' => 'week',
            ],
            'tempo' => [
                'default' => '3010',
                'applyPer' => 'week',
            ],
            'watts' => null,
            'weight' => [
                'mode' => 'manual',
                'oneRepMaxModifier' => 100,
                'default' => 5,
                'applyPer' => 'session',
            ],
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'id' => 82,
                'sort' => 0,
            ],
            [
                'id' => 258,
                'sort' => 0,
            ],
        ],
    ],
    [
        'id' => 12,
        'name' => 'Superman plank',
        'category_id' => null,
        'template_id' => 2,
        'video_url' => 'https://www.youtube.com/shorts/6AT8zcAAAj8',
        'instructions' => 'Keine Lordose in der LWS',
        'config' => [
            'settings' => [
                'reps',
                'weight',
                'tempo',
                'rest',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 4,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => [
                'default' => 60,
                'applyPer' => 'week',
            ],
            'tempo' => [
                'default' => '3010',
                'applyPer' => 'week',
            ],
            'watts' => null,
            'weight' => [
                'mode' => 'manual',
                'oneRepMaxModifier' => 100,
                'default' => 5,
                'applyPer' => 'session',
            ],
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [],
    ],
];
