<?php

return [
    [
        'name' => 'ATG Split Squat',
        'category' => 'exercise_category:strength',
        'template' => 'Strength (Manual Coach)',
        'video_url' => 'https://www.youtube.com/shorts/LHX34TpJxbQ',
        'instructions' => 'Knie muss über Fussspitze kommen ',
        'config' => [
            'settings' => [
                'reps',
                'weight',
                'tempo',
                'rest',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 4,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => [
                'default' => 60,
                'applyPer' => 'week',
            ],
            'tempo' => [
                'default' => '3010',
                'applyPer' => 'week',
            ],
            'watts' => null,
            'weight' => [
                'mode' => 'manual',
                'oneRepMaxModifier' => 100,
                'default' => 5,
                'applyPer' => 'session',
            ],
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'tag' => 'exercise_equipment:db',
                'sort' => 0,
            ],
            [
                'tag' => 'exercise_modifiers:front-foot-flat-on-floor',
                'sort' => 0,
            ],
        ],
    ],
    [
        'name' => 'Back Squat',
        'category' => 'exercise_category:strength',
        'template' => 'Strength (Automatic)',
        'video_url' => 'https://www.youtube.com/watch?v=CPgCggIyn-g',
        'instructions' => 'So lange runter bis rücken gerade ist',
        'config' => [
            'settings' => [
                'reps',
                'weight',
                'tempo',
                'rest',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'odd',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 4,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'automatic',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => [
                'default' => 60,
                'applyPer' => 'week',
            ],
            'tempo' => [
                'default' => '3010',
                'applyPer' => 'week',
            ],
            'watts' => null,
            'weight' => [
                'mode' => 'automatic',
                'oneRepMaxModifier' => 100,
                'default' => 5,
                'applyPer' => 'session',
            ],
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'tag' => 'exercise_modifiers:heel-elevated',
                'sort' => 0,
            ],
        ],
    ],
    [
        'name' => 'Chin-Up',
        'category' => 'exercise_category:strength',
        'template' => null,
        'video_url' => 'https://youtu.be/jWG018GIUjY',
        'instructions' => 'Gleichmässig runter',
        'config' => [
            'settings' => [
                'reps',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 5,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'tag' => 'exercise_modifiers:neutral',
                'sort' => 0,
            ],
            [
                'tag' => 'exercise_modifiers:eccentric-only',
                'sort' => 0,
            ],
        ],
    ],
    [
        'name' => 'core plank + side plank',
        'category' => 'exercise_category:core',
        'template' => null,
        'video_url' => 'https://www.youtube.com/shorts/tJwHo9kg5GI',
        'instructions' => 'Brustkasten raus!',
        'config' => [
            'settings' => [
                'reps',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 7,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [],
    ],
    [
        'name' => 'Dip',
        'category' => 'exercise_category:strength',
        'template' => null,
        'video_url' => 'https://youtu.be/dG99wTA7d2U',
        'instructions' => 'Ellenbogen drin behalten',
        'config' => [
            'settings' => [
                'reps',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 5,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [],
    ],
    [
        'name' => 'Front Squat',
        'category' => 'exercise_category:strength',
        'template' => 'Strength (Automatic)',
        'video_url' => 'https://www.youtube.com/shorts/iVtH8lZATdQ',
        'instructions' => 'Ellenbogen hochnehmen die ganze Zeit',
        'config' => [
            'settings' => [
                'reps',
                'weight',
                'tempo',
                'rest',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'odd',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 4,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'automatic',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => [
                'default' => 60,
                'applyPer' => 'week',
            ],
            'tempo' => [
                'default' => '3010',
                'applyPer' => 'week',
            ],
            'watts' => null,
            'weight' => [
                'mode' => 'automatic',
                'oneRepMaxModifier' => 100,
                'default' => 5,
                'applyPer' => 'session',
            ],
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'tag' => 'exercise_modifiers:heel-elevated',
                'sort' => 0,
            ],
            [
                'tag' => 'exercise_equipment:bb',
                'sort' => 0,
            ],
        ],
    ],
    [
        'name' => 'Hütchensprint li/re',
        'category' => 'exercise_category:lateral',
        'template' => null,
        'video_url' => null,
        'instructions' => null,
        'config' => [
            'settings' => [
                'reps',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 5,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'tag' => 'exercise_equipment:hutchen',
                'sort' => 0,
            ],
            [
                'tag' => 'exercise_modifiers:outdoor',
                'sort' => 0,
            ],
            [
                'tag' => 'exercise_modifiers:halle',
                'sort' => 0,
            ],
        ],
    ],
    [
        'name' => 'Interval Bike Extensiv Indoor',
        'category' => 'exercise_category:interval',
        'template' => 'Interval Extensiv',
        'video_url' => 'https://www.youtube.com/shorts/jN3HeMMvB5o',
        'instructions' => '',
        'config' => [
            'settings' => [
                'heartRate',
                'duration',
                'heartRateZone',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Interval',
                'default' => 7,
            ],
            'distance' => null,
            'duration' => [
                'unit' => 'minutes',
                'default' => 1,
                'applyPer' => 'session',
            ],
            'heartRate' => [
                'default' => '140',
                'applyPer' => 'session',
            ],
            'heartRateZone' => [
                'default' => '3',
                'applyPer' => 'session',
            ],
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'tag' => 'exercise_equipment:indoor-bike',
                'sort' => 0,
            ],
            [
                'tag' => 'exercise_modifiers:indoor',
                'sort' => 0,
            ],
        ],
    ],
    [
        'name' => 'Interval Bike Extensiv Outdoor',
        'category' => 'exercise_category:interval',
        'template' => 'Interval Extensiv',
        'video_url' => null,
        'instructions' => null,
        'config' => [
            'settings' => [
                'heartRate',
                'duration',
                'heartRateZone',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Interval',
                'default' => 7,
            ],
            'distance' => null,
            'duration' => [
                'unit' => 'minutes',
                'default' => 1,
                'applyPer' => 'session',
            ],
            'heartRate' => [
                'default' => '140',
                'applyPer' => 'session',
            ],
            'heartRateZone' => [
                'default' => '3',
                'applyPer' => 'session',
            ],
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'tag' => 'exercise_equipment:outdoor-bike',
                'sort' => 0,
            ],
            [
                'tag' => 'exercise_modifiers:outdoor',
                'sort' => 0,
            ],
        ],
    ],
    [
        'name' => 'Interval Jogging Extensiv Indoor',
        'category' => 'exercise_category:interval',
        'template' => 'Interval Extensiv',
        'video_url' => 'https://www.youtube.com/shorts/sMXvl_iOW88',
        'instructions' => null,
        'config' => [
            'settings' => [
                'heartRate',
                'duration',
                'heartRateZone',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Interval',
                'default' => 7,
            ],
            'distance' => null,
            'duration' => [
                'unit' => 'minutes',
                'default' => 1,
                'applyPer' => 'session',
            ],
            'heartRate' => [
                'default' => '140',
                'applyPer' => 'session',
            ],
            'heartRateZone' => [
                'default' => '3',
                'applyPer' => 'session',
            ],
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'tag' => 'exercise_equipment:treadmill',
                'sort' => 0,
            ],
            [
                'tag' => 'exercise_modifiers:indoor',
                'sort' => 0,
            ],
        ],
    ],
    [
        'name' => 'Interval Jogging Extensiv Outdoor',
        'category' => 'exercise_category:interval',
        'template' => 'Interval Extensiv',
        'video_url' => null,
        'instructions' => null,
        'config' => [
            'settings' => [
                'heartRate',
                'duration',
                'heartRateZone',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Interval',
                'default' => 7,
            ],
            'distance' => null,
            'duration' => [
                'unit' => 'minutes',
                'default' => 1,
                'applyPer' => 'session',
            ],
            'heartRate' => [
                'default' => '140',
                'applyPer' => 'session',
            ],
            'heartRateZone' => [
                'default' => '3',
                'applyPer' => 'session',
            ],
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'tag' => 'exercise_modifiers:outdoor',
                'sort' => 0,
            ],
        ],
    ],
    [
        'name' => 'kNIEBEUGE HINTEN AUF BRETT LH',
        'category' => 'exercise_category:strength',
        'template' => 'Strength (Automatic)',
        'video_url' => null,
        'instructions' => null,
        'config' => [
            'settings' => [
                'reps',
                'weight',
                'tempo',
                'rest',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'odd',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 4,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'automatic',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => [
                'default' => 60,
                'applyPer' => 'week',
            ],
            'tempo' => [
                'default' => '3010',
                'applyPer' => 'week',
            ],
            'watts' => null,
            'weight' => [
                'mode' => 'automatic',
                'oneRepMaxModifier' => 100,
                'default' => 5,
                'applyPer' => 'session',
            ],
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [],
    ],
    [
        'name' => 'Koordination Ragettli Parcour',
        'category' => 'exercise_category:coordination',
        'template' => null,
        'video_url' => 'https://www.youtube.com/watch?v=AfD736-n0e8',
        'instructions' => 'Nicht verletzten',
        'config' => [
            'settings' => [
                'reps',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 5,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [],
    ],
    [
        'name' => 'Lastheben',
        'category' => 'exercise_category:strength',
        'template' => 'Strength (Automatic)',
        'video_url' => 'https://www.youtube.com/watch?v=CPgCggIyn-g',
        'instructions' => 'Stange immer am Körper lassen',
        'config' => [
            'settings' => [
                'reps',
                'weight',
                'tempo',
                'rest',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'odd',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 4,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'automatic',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => [
                'default' => 60,
                'applyPer' => 'week',
            ],
            'tempo' => [
                'default' => '3010',
                'applyPer' => 'week',
            ],
            'watts' => null,
            'weight' => [
                'mode' => 'automatic',
                'oneRepMaxModifier' => 100,
                'default' => 5,
                'applyPer' => 'session',
            ],
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'tag' => 'exercise_modifiers:heel-elevated',
                'sort' => 0,
            ],
        ],
    ],
    [
        'name' => 'Lastheben 2',
        'category' => 'exercise_category:strength',
        'template' => 'Strength (Manual Coach)',
        'video_url' => null,
        'instructions' => null,
        'config' => [
            'settings' => [
                'reps',
                'weight',
                'tempo',
                'rest',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 4,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => [
                'default' => 60,
                'applyPer' => 'week',
            ],
            'tempo' => [
                'default' => '3010',
                'applyPer' => 'week',
            ],
            'watts' => null,
            'weight' => [
                'mode' => 'manual',
                'oneRepMaxModifier' => 100,
                'default' => 5,
                'applyPer' => 'session',
            ],
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'tag' => 'exercise_equipment:bb',
                'sort' => 0,
            ],
            [
                'tag' => 'exercise_modifiers:heel-elevated',
                'sort' => 0,
            ],
        ],
    ],
    [
        'name' => 'Push Press',
        'category' => 'exercise_category:strength',
        'template' => null,
        'video_url' => 'https://youtu.be/isXQmhH6AEM',
        'instructions' => 'Sehr Explosiv Arbieten',
        'config' => [
            'settings' => [
                'reps',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 5,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'tag' => 'exercise_equipment:bb',
                'sort' => 0,
            ],
            [
                'tag' => 'exercise_modifiers:medium-grip',
                'sort' => 0,
            ],
            [
                'tag' => 'exercise_modifiers:behind-the-neck',
                'sort' => 0,
            ],
        ],
    ],
    [
        'name' => 'Skischuh Squatjump',
        'category' => 'exercise_category:ski',
        'template' => 'Strength (Manual Coach)',
        'video_url' => null,
        'instructions' => 'Hands on hip, Executive a Jump 90 degrees max and Full length with skiboots',
        'config' => [
            'settings' => [
                'reps',
                'weight',
                'tempo',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 4,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => '4',
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => [
                'default' => 60,
                'applyPer' => 'week',
            ],
            'tempo' => [
                'default' => '30x0',
                'applyPer' => 'week',
            ],
            'watts' => [
                'default' => 100,
                'applyPer' => 'session',
            ],
            'weight' => [
                'mode' => 'manual',
                'oneRepMaxModifier' => 100,
                'default' => 10,
                'applyPer' => 'session',
            ],
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'tag' => 'exercise_equipment:skiboots',
                'sort' => 0,
            ],
            [
                'tag' => 'exercise_modifiers:hand-on-hip',
                'sort' => 0,
            ],
        ],
    ],
    [
        'name' => 'Slalom Furtschellas',
        'category' => 'exercise_category:ski',
        'template' => null,
        'video_url' => null,
        'instructions' => null,
        'config' => [
            'settings' => [
                'reps',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Run',
                'default' => 10,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => '48',
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => 'Gates',
                'applyPer' => 'session',
            ],
            'rest' => null,
            'tempo' => null,
            'watts' => null,
            'weight' => null,
            'preview' => [
                'weeks' => 1,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'tag' => 'exercise_equipment:long-gates',
                'sort' => 0,
            ],
            [
                'tag' => 'exercise_modifiers:straight-setting',
                'sort' => 0,
            ],
        ],
    ],
    [
        'name' => 'Step up',
        'category' => 'exercise_category:strength',
        'template' => 'Strength (Manual Coach)',
        'video_url' => 'https://www.youtube.com/shorts/r-wWtYEzYIw',
        'instructions' => 'Ohne Schwung',
        'config' => [
            'settings' => [
                'reps',
                'weight',
                'tempo',
                'rest',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 4,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => [
                'default' => 60,
                'applyPer' => 'week',
            ],
            'tempo' => [
                'default' => '3010',
                'applyPer' => 'week',
            ],
            'watts' => null,
            'weight' => [
                'mode' => 'manual',
                'oneRepMaxModifier' => 100,
                'default' => 5,
                'applyPer' => 'session',
            ],
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [
            [
                'tag' => 'exercise_equipment:db',
                'sort' => 0,
            ],
            [
                'tag' => 'exercise_modifiers:foot-neutral',
                'sort' => 0,
            ],
        ],
    ],
    [
        'name' => 'Superman plank',
        'category' => 'exercise_category:core',
        'template' => 'Strength (Manual Coach)',
        'video_url' => 'https://www.youtube.com/shorts/6AT8zcAAAj8',
        'instructions' => 'Keine Lordose in der LWS',
        'config' => [
            'settings' => [
                'reps',
                'weight',
                'tempo',
                'rest',
            ],
            'overrides' => [
                'cells' => [],
                'weeks' => [],
            ],
            'sets' => [
                'deload' => 'none',
                'deloadBy' => 1,
                'label' => 'Set',
                'default' => 4,
            ],
            'distance' => null,
            'duration' => null,
            'heartRate' => null,
            'heartRateZone' => null,
            'pace' => null,
            'reps' => [
                'mode' => 'manual',
                'default' => 10,
                'stepDownInterval' => 2,
                'decrement' => 2,
                'minimum' => 1,
                'label' => '',
                'applyPer' => 'session',
            ],
            'rest' => [
                'default' => 60,
                'applyPer' => 'week',
            ],
            'tempo' => [
                'default' => '3010',
                'applyPer' => 'week',
            ],
            'watts' => null,
            'weight' => [
                'mode' => 'manual',
                'oneRepMaxModifier' => 100,
                'default' => 5,
                'applyPer' => 'session',
            ],
            'preview' => [
                'weeks' => 5,
                'sessionsPerWeek' => 1,
                'measuredReps' => 1,
                'measuredWeight' => 50,
                'targetGoal' => 10,
            ],
        ],
        'tags' => [],
    ],
];
