<?php

return [
    [
        'scope' => 'equipment',
        'name' => 'Barbell',
        'short_name' => null,
        'slug' => 'barbell',
        'sort_order' => 0,
    ],
    [
        'scope' => 'equipment',
        'name' => 'Bodyweight',
        'short_name' => null,
        'slug' => 'bodyweight',
        'sort_order' => 0,
    ],
    [
        'scope' => 'equipment',
        'name' => 'Cable Machine',
        'short_name' => null,
        'slug' => 'cable-machine',
        'sort_order' => 0,
    ],
    [
        'scope' => 'equipment',
        'name' => 'Dumbbell',
        'short_name' => null,
        'slug' => 'dumbbell',
        'sort_order' => 0,
    ],
    [
        'scope' => 'equipment',
        'name' => 'Kettlebell',
        'short_name' => null,
        'slug' => 'kettlebell',
        'sort_order' => 0,
    ],
    [
        'scope' => 'equipment',
        'name' => 'Resistance Band',
        'short_name' => null,
        'slug' => 'resistance-band',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_category',
        'name' => 'Strength',
        'short_name' => null,
        'slug' => 'strength',
        'sort_order' => 0,
        'color' => 'red',
        'children' => [
            [
                'name' => 'Absolute Strength',
                'short_name' => null,
                'slug' => 'absolute-strength',
                'sort_order' => 0,
            ],
            [
                'name' => 'Endurance Strength',
                'short_name' => null,
                'slug' => 'endurance-strength',
                'sort_order' => 1,
            ],
            [
                'name' => 'Explosive Strength',
                'short_name' => null,
                'slug' => 'explosive-strength',
                'sort_order' => 2,
            ],
            [
                'name' => 'Hypertrophie',
                'short_name' => null,
                'slug' => 'hypertrophie',
                'sort_order' => 3,
            ],
            [
                'name' => 'Isometric Strength',
                'short_name' => null,
                'slug' => 'isometric-strength',
                'sort_order' => 4,
            ],
            [
                'name' => 'Maximum Strength',
                'short_name' => null,
                'slug' => 'maximum-strength',
                'sort_order' => 5,
            ],
            [
                'name' => 'Reactive Strength',
                'short_name' => null,
                'slug' => 'reactive-strength',
                'sort_order' => 6,
            ],
            [
                'name' => 'Relative Strength',
                'short_name' => null,
                'slug' => 'relative-strength',
                'sort_order' => 7,
            ],
            [
                'name' => 'Speed Strength',
                'short_name' => null,
                'slug' => 'speed-strength',
                'sort_order' => 8,
            ],
        ],
    ],
    [
        'scope' => 'exercise_category',
        'name' => 'Endurance',
        'short_name' => null,
        'slug' => 'endurance',
        'sort_order' => 1,
        'color' => 'purple',
        'children' => [
            [
                'name' => 'Interval',
                'short_name' => null,
                'slug' => 'interval',
                'sort_order' => 0,
            ],
        ],
    ],
    [
        'scope' => 'exercise_category',
        'name' => 'Coordination',
        'short_name' => null,
        'slug' => 'coordination',
        'sort_order' => 2,
        'color' => 'orange',
    ],
    [
        'scope' => 'exercise_category',
        'name' => 'Velocity',
        'short_name' => null,
        'slug' => 'velocity',
        'sort_order' => 3,
        'color' => 'amber',
        'children' => [
            [
                'name' => 'Acceleration ',
                'short_name' => null,
                'slug' => 'acceleration',
                'sort_order' => 0,
                'children' => [
                    [
                        'name' => 'Fliegend sprint',
                        'short_name' => null,
                        'slug' => 'fliegend-sprint',
                        'sort_order' => 0,
                    ],
                ],
            ],
            [
                'name' => 'Agillity',
                'short_name' => null,
                'slug' => 'agillity',
                'sort_order' => 1,
            ],
            [
                'name' => 'Change of direction ',
                'short_name' => null,
                'slug' => 'change-of-direction',
                'sort_order' => 2,
                'children' => [
                    [
                        'name' => 'Frontal',
                        'short_name' => null,
                        'slug' => 'frontal',
                        'sort_order' => 0,
                    ],
                    [
                        'name' => 'Lateral',
                        'short_name' => null,
                        'slug' => 'lateral',
                        'sort_order' => 1,
                    ],
                ],
            ],
            [
                'name' => 'Frequence',
                'short_name' => null,
                'slug' => 'frequence',
                'sort_order' => 3,
            ],
            [
                'name' => 'Max velocity',
                'short_name' => null,
                'slug' => 'max-velocity',
                'sort_order' => 4,
            ],
            [
                'name' => 'Plyometrics',
                'short_name' => null,
                'slug' => 'plyometrics',
                'sort_order' => 5,
            ],
            [
                'name' => 'Repeated Sprint Ability',
                'short_name' => null,
                'slug' => 'repeated-sprint-ability',
                'sort_order' => 6,
            ],
            [
                'name' => 'Speed endurance ',
                'short_name' => null,
                'slug' => 'speed-endurance',
                'sort_order' => 7,
            ],
        ],
    ],
    [
        'scope' => 'exercise_category',
        'name' => 'Mobility',
        'short_name' => null,
        'slug' => 'mobility',
        'sort_order' => 4,
        'color' => 'indigo',
    ],
    [
        'scope' => 'exercise_category',
        'name' => 'Rehab',
        'short_name' => null,
        'slug' => 'rehab',
        'sort_order' => 5,
        'color' => 'pink',
        'children' => [
            [
                'name' => 'Achilles',
                'short_name' => null,
                'slug' => 'achilles',
                'sort_order' => 0,
                'children' => [
                    [
                        'name' => 'Acute Protection Phase 0-2 Weeks',
                        'short_name' => null,
                        'slug' => 'acute-protection-phase-0-2-weeks',
                        'sort_order' => 0,
                    ],
                    [
                        'name' => 'Early Loading Phase 2-6 Weeks',
                        'short_name' => null,
                        'slug' => 'early-loading-phase-2-6-weeks',
                        'sort_order' => 1,
                    ],
                ],
            ],
            [
                'name' => 'ACL',
                'short_name' => null,
                'slug' => 'acl',
                'sort_order' => 1,
                'children' => [
                    [
                        'name' => 'Acute Phase 0-2 Weeks',
                        'short_name' => null,
                        'slug' => 'acute-phase-0-2-weeks',
                        'sort_order' => 0,
                    ],
                    [
                        'name' => 'Phase 2 Early Strength 2-6 Week',
                        'short_name' => null,
                        'slug' => 'phase-2-early-strength-2-6-week',
                        'sort_order' => 1,
                    ],
                ],
            ],
            [
                'name' => 'Meniscus',
                'short_name' => null,
                'slug' => 'meniscus',
                'sort_order' => 2,
            ],
        ],
    ],
    [
        'scope' => 'exercise_category',
        'name' => 'Ski',
        'short_name' => null,
        'slug' => 'ski',
        'sort_order' => 6,
        'color' => 'blue',
    ],
    [
        'scope' => 'exercise_category',
        'name' => 'Recovery',
        'short_name' => null,
        'slug' => 'recovery',
        'sort_order' => 7,
        'color' => 'green',
        'children' => [
            [
                'name' => 'Foam Rolling ',
                'short_name' => null,
                'slug' => 'foam-rolling',
                'sort_order' => 0,
                'children' => [
                    [
                        'name' => 'Legs',
                        'short_name' => null,
                        'slug' => 'legs',
                        'sort_order' => 0,
                    ],
                ],
            ],
            [
                'name' => 'Mobility',
                'short_name' => null,
                'slug' => 'mobility-1',
                'sort_order' => 1,
                'children' => [
                    [
                        'name' => 'Hipmobility',
                        'short_name' => null,
                        'slug' => 'hipmobility',
                        'sort_order' => 0,
                        'children' => [
                            [
                                'name' => '90/90',
                                'short_name' => null,
                                'slug' => '9090',
                                'sort_order' => 0,
                            ],
                            [
                                'name' => 'Standing Hip Rotation',
                                'short_name' => null,
                                'slug' => 'standing-hip-rotation',
                                'sort_order' => 1,
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],
    [
        'scope' => 'exercise_category',
        'name' => 'Core',
        'short_name' => null,
        'slug' => 'core',
        'sort_order' => 8,
        'color' => 'teal',
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Ab Wheel',
        'short_name' => null,
        'slug' => 'ab-wheel',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Band',
        'short_name' => null,
        'slug' => 'band',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Bands',
        'short_name' => null,
        'slug' => 'bands',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'BB',
        'short_name' => null,
        'slug' => 'bb',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Cable',
        'short_name' => null,
        'slug' => 'cable',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Cambered Bar',
        'short_name' => null,
        'slug' => 'cambered-bar',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'DB',
        'short_name' => null,
        'slug' => 'db',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'EZ Bar',
        'short_name' => null,
        'slug' => 'ez-bar',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Foam Roller',
        'short_name' => null,
        'slug' => 'foam-roller',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Glute Ham Developer',
        'short_name' => null,
        'slug' => 'glute-ham-developer',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Head Harness',
        'short_name' => null,
        'slug' => 'head-harness',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Hütchen',
        'short_name' => null,
        'slug' => 'hutchen',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Indoor Bike',
        'short_name' => null,
        'slug' => 'indoor-bike',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Leg Curl Machine',
        'short_name' => null,
        'slug' => 'leg-curl-machine',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Leg Press',
        'short_name' => null,
        'slug' => 'leg-press',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'LH',
        'short_name' => null,
        'slug' => 'lh',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Machine',
        'short_name' => null,
        'slug' => 'machine',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Med Ball',
        'short_name' => null,
        'slug' => 'med-ball',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Outdoor Bike',
        'short_name' => null,
        'slug' => 'outdoor-bike',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Pinch Block',
        'short_name' => null,
        'slug' => 'pinch-block',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Pinch Card',
        'short_name' => null,
        'slug' => 'pinch-card',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Resistance Bands',
        'short_name' => null,
        'slug' => 'resistance-bands',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Rings',
        'short_name' => null,
        'slug' => 'rings',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Rope',
        'short_name' => null,
        'slug' => 'rope',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Safety Bar',
        'short_name' => null,
        'slug' => 'safety-bar',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Shoulder Horn',
        'short_name' => null,
        'slug' => 'shoulder-horn',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Skiboots',
        'short_name' => null,
        'slug' => 'skiboots',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Swiss Ball',
        'short_name' => null,
        'slug' => 'swiss-ball',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Thick Angled Bar',
        'short_name' => null,
        'slug' => 'thick-angled-bar',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Thick Bar',
        'short_name' => null,
        'slug' => 'thick-bar',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Thick EZ Bar',
        'short_name' => null,
        'slug' => 'thick-ez-bar',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Thick Multi-Angled Bar',
        'short_name' => null,
        'slug' => 'thick-multi-angled-bar',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Thick Parallel Bar',
        'short_name' => null,
        'slug' => 'thick-parallel-bar',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Thor\'s Hammer',
        'short_name' => null,
        'slug' => 'thors-hammer',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Trap Bar',
        'short_name' => null,
        'slug' => 'trap-bar',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'treadmill',
        'short_name' => null,
        'slug' => 'treadmill',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Triceps Bar',
        'short_name' => null,
        'slug' => 'triceps-bar',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Weight Plate',
        'short_name' => null,
        'slug' => 'weight-plate',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Wrist Roller',
        'short_name' => null,
        'slug' => 'wrist-roller',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => '(2-1)',
        'short_name' => null,
        'slug' => '2-1',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => '15° Decline',
        'short_name' => null,
        'slug' => '15-decline',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => '15° Incline',
        'short_name' => null,
        'slug' => '15-incline',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => '2” Deficit',
        'short_name' => null,
        'slug' => '2-deficit',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => '25° Decline',
        'short_name' => null,
        'slug' => '25-decline',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => '3-Pause Eccentric',
        'short_name' => null,
        'slug' => '3-pause-eccentric',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => '35˚ Incline',
        'short_name' => null,
        'slug' => '350-incline',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => '35° Decline',
        'short_name' => null,
        'slug' => '35-decline',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => '35° Incline',
        'short_name' => null,
        'slug' => '35-incline',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => '4” Deficit',
        'short_name' => null,
        'slug' => '4-deficit',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => '45˚ Incline',
        'short_name' => null,
        'slug' => '450-incline',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => '45° Incline',
        'short_name' => null,
        'slug' => '45-incline',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => '55˚ Incline',
        'short_name' => null,
        'slug' => '550-incline',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => '55° Incline',
        'short_name' => null,
        'slug' => '55-incline',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => '65° Incline',
        'short_name' => null,
        'slug' => '65-incline',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Above Knee',
        'short_name' => null,
        'slug' => 'above-knee',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Accentuated Eccentric',
        'short_name' => null,
        'slug' => 'accentuated-eccentric',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Alternated',
        'short_name' => null,
        'slug' => 'alternated',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Arc',
        'short_name' => null,
        'slug' => 'arc',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Arm in Front',
        'short_name' => null,
        'slug' => 'arm-in-front',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Arm to Side',
        'short_name' => null,
        'slug' => 'arm-to-side',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Arnold',
        'short_name' => null,
        'slug' => 'arnold',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Assisted',
        'short_name' => null,
        'slug' => 'assisted',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'B Stance',
        'short_name' => null,
        'slug' => 'b-stance',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Back',
        'short_name' => null,
        'slug' => 'back',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Back Foot Elevated',
        'short_name' => null,
        'slug' => 'back-foot-elevated',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Banded',
        'short_name' => null,
        'slug' => 'banded',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Behind Neck',
        'short_name' => null,
        'slug' => 'behind-neck',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Behind the Neck',
        'short_name' => null,
        'slug' => 'behind-the-neck',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Below Knee',
        'short_name' => null,
        'slug' => 'below-knee',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Bent-Knee',
        'short_name' => null,
        'slug' => 'bent-knee',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Bent-Over',
        'short_name' => null,
        'slug' => 'bent-over',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Bilateral',
        'short_name' => null,
        'slug' => 'bilateral',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Birddog',
        'short_name' => null,
        'slug' => 'birddog',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Bottom Range',
        'short_name' => null,
        'slug' => 'bottom-range',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Bulgarian',
        'short_name' => null,
        'slug' => 'bulgarian',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Califorina',
        'short_name' => null,
        'slug' => 'califorina',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'California',
        'short_name' => null,
        'slug' => 'california',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Close Grip',
        'short_name' => null,
        'slug' => 'close-grip',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Cobra',
        'short_name' => null,
        'slug' => 'cobra',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Commerford',
        'short_name' => null,
        'slug' => 'commerford',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Contralateral',
        'short_name' => null,
        'slug' => 'contralateral',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Copenhagen',
        'short_name' => null,
        'slug' => 'copenhagen',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Cuban Press',
        'short_name' => null,
        'slug' => 'cuban-press',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Cyclist',
        'short_name' => null,
        'slug' => 'cyclist',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Dips',
        'short_name' => null,
        'slug' => 'dips',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Dorsiflexed',
        'short_name' => null,
        'slug' => 'dorsiflexed',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Drop',
        'short_name' => null,
        'slug' => 'drop',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Duchaine',
        'short_name' => null,
        'slug' => 'duchaine',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Duck',
        'short_name' => null,
        'slug' => 'duck',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Eccentric Only',
        'short_name' => null,
        'slug' => 'eccentric-only',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Elbow on Knee',
        'short_name' => null,
        'slug' => 'elbow-on-knee',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Elbow Out',
        'short_name' => null,
        'slug' => 'elbow-out',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'End Range',
        'short_name' => null,
        'slug' => 'end-range',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'External Rotation',
        'short_name' => null,
        'slug' => 'external-rotation',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Face-Away',
        'short_name' => null,
        'slug' => 'face-away',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Facing',
        'short_name' => null,
        'slug' => 'facing',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Feet Down',
        'short_name' => null,
        'slug' => 'feet-down',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Feet High',
        'short_name' => null,
        'slug' => 'feet-high',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Feet In',
        'short_name' => null,
        'slug' => 'feet-in',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Feet Low',
        'short_name' => null,
        'slug' => 'feet-low',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Feet Neutral',
        'short_name' => null,
        'slug' => 'feet-neutral',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Feet on Med Ball',
        'short_name' => null,
        'slug' => 'feet-on-med-ball',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Feet on Swiss Ball',
        'short_name' => null,
        'slug' => 'feet-on-swiss-ball',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Feet Out',
        'short_name' => null,
        'slug' => 'feet-out',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Feet Up',
        'short_name' => null,
        'slug' => 'feet-up',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Flat',
        'short_name' => null,
        'slug' => 'flat',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Floor',
        'short_name' => null,
        'slug' => 'floor',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Foot High',
        'short_name' => null,
        'slug' => 'foot-high',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Foot In',
        'short_name' => null,
        'slug' => 'foot-in',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Foot Neutral',
        'short_name' => null,
        'slug' => 'foot-neutral',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Foot Out',
        'short_name' => null,
        'slug' => 'foot-out',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Front',
        'short_name' => null,
        'slug' => 'front',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Front Foot',
        'short_name' => null,
        'slug' => 'front-foot',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Front Foot Elevated',
        'short_name' => null,
        'slug' => 'front-foot-elevated',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Front Foot Flat On Floor',
        'short_name' => null,
        'slug' => 'front-foot-flat-on-floor',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Front Rack',
        'short_name' => null,
        'slug' => 'front-rack',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Full',
        'short_name' => null,
        'slug' => 'full',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Goblet',
        'short_name' => null,
        'slug' => 'goblet',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Hack',
        'short_name' => null,
        'slug' => 'hack',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Half Kneeling',
        'short_name' => null,
        'slug' => 'half-kneeling-1',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Half Lay',
        'short_name' => null,
        'slug' => 'half-lay',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Half-Kneeling',
        'short_name' => null,
        'slug' => 'half-kneeling',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Halle',
        'short_name' => null,
        'slug' => 'halle',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Hamstring',
        'short_name' => null,
        'slug' => 'hamstring',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Hamstring Walk',
        'short_name' => null,
        'slug' => 'hamstring-walk',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Hand on',
        'short_name' => null,
        'slug' => 'hand-on',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Hand on hip',
        'short_name' => null,
        'slug' => 'hand-on-hip',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Hanging',
        'short_name' => null,
        'slug' => 'hanging',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Hatfield',
        'short_name' => null,
        'slug' => 'hatfield',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Heel Elevated',
        'short_name' => null,
        'slug' => 'heel-elevated',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Heels Elevated',
        'short_name' => null,
        'slug' => 'heels-elevated',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'High Handles',
        'short_name' => null,
        'slug' => 'high-handles',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'High Pulley',
        'short_name' => null,
        'slug' => 'high-pulley',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Hip Extension',
        'short_name' => null,
        'slug' => 'hip-extension',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Horizontal',
        'short_name' => null,
        'slug' => 'horizontal',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Incline',
        'short_name' => null,
        'slug' => 'incline',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Indoor',
        'short_name' => null,
        'slug' => 'indoor',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Inertia',
        'short_name' => null,
        'slug' => 'inertia',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Internal Rotation',
        'short_name' => null,
        'slug' => 'internal-rotation',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Ipsilateral',
        'short_name' => null,
        'slug' => 'ipsilateral',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Janda',
        'short_name' => null,
        'slug' => 'janda',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Javelin',
        'short_name' => null,
        'slug' => 'javelin',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Knee Flexion',
        'short_name' => null,
        'slug' => 'knee-flexion',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Kneeling',
        'short_name' => null,
        'slug' => 'kneeling',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'L-Style',
        'short_name' => null,
        'slug' => 'l-style',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Large',
        'short_name' => null,
        'slug' => 'large',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Lean 45°',
        'short_name' => null,
        'slug' => 'lean-45',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Lean-Away',
        'short_name' => null,
        'slug' => 'lean-away',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Leg Press',
        'short_name' => null,
        'slug' => 'leg-press',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Long Lever',
        'short_name' => null,
        'slug' => 'long-lever',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Low Handles',
        'short_name' => null,
        'slug' => 'low-handles',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Low Pulley',
        'short_name' => null,
        'slug' => 'low-pulley',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Lying',
        'short_name' => null,
        'slug' => 'lying',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'McGill',
        'short_name' => null,
        'slug' => 'mcgill',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Medium Grip',
        'short_name' => null,
        'slug' => 'medium-grip',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Medium Stance',
        'short_name' => null,
        'slug' => 'medium-stance',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Mid Pulley',
        'short_name' => null,
        'slug' => 'mid-pulley',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Mid Range',
        'short_name' => null,
        'slug' => 'mid-range',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Mid Thigh',
        'short_name' => null,
        'slug' => 'mid-thigh',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Muscle Snatch',
        'short_name' => null,
        'slug' => 'muscle-snatch',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Narrow Stance',
        'short_name' => null,
        'slug' => 'narrow-stance',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Neutral',
        'short_name' => null,
        'slug' => 'neutral',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Offset',
        'short_name' => null,
        'slug' => 'offset',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'One-Arm',
        'short_name' => null,
        'slug' => 'one-arm',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'One-Leg',
        'short_name' => null,
        'slug' => 'one-leg',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Outdoor',
        'short_name' => null,
        'slug' => 'outdoor',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Overhead',
        'short_name' => null,
        'slug' => 'overhead',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Partial',
        'short_name' => null,
        'slug' => 'partial',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Petersen',
        'short_name' => null,
        'slug' => 'petersen',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Pin Touch',
        'short_name' => null,
        'slug' => 'pin-touch',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Pistol',
        'short_name' => null,
        'slug' => 'pistol',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Plantarflexed',
        'short_name' => null,
        'slug' => 'plantarflexed',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Pre-Stretch',
        'short_name' => null,
        'slug' => 'pre-stretch',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Progression',
        'short_name' => null,
        'slug' => 'progression',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Pronated',
        'short_name' => null,
        'slug' => 'pronated',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Prone',
        'short_name' => null,
        'slug' => 'prone',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Quad',
        'short_name' => null,
        'slug' => 'quad',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Rack',
        'short_name' => null,
        'slug' => 'rack',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Razor',
        'short_name' => null,
        'slug' => 'razor',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Reverse',
        'short_name' => null,
        'slug' => 'reverse',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Romanian',
        'short_name' => null,
        'slug' => 'romanian',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Romanian Rhythm',
        'short_name' => null,
        'slug' => 'romanian-rhythm',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Rope to Forehead',
        'short_name' => null,
        'slug' => 'rope-to-forehead',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Rope to Neck',
        'short_name' => null,
        'slug' => 'rope-to-neck',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Rotation',
        'short_name' => null,
        'slug' => 'rotation',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Russian',
        'short_name' => null,
        'slug' => 'russian',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Scott',
        'short_name' => null,
        'slug' => 'scott',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Seated',
        'short_name' => null,
        'slug' => 'seated',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Semi-pronated',
        'short_name' => null,
        'slug' => 'semi-pronated',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Semi-Supinated',
        'short_name' => null,
        'slug' => 'semi-supinated',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Short Lever',
        'short_name' => null,
        'slug' => 'short-lever',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Side',
        'short_name' => null,
        'slug' => 'side',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Side Lying',
        'short_name' => null,
        'slug' => 'side-lying',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Side to Side',
        'short_name' => null,
        'slug' => 'side-to-side',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Sideway',
        'short_name' => null,
        'slug' => 'sideway',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Single-Leg Romanian',
        'short_name' => null,
        'slug' => 'single-leg-romanian',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Sissy',
        'short_name' => null,
        'slug' => 'sissy',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Small',
        'short_name' => null,
        'slug' => 'small',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Sots',
        'short_name' => null,
        'slug' => 'sots',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Spider',
        'short_name' => null,
        'slug' => 'spider',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Squat',
        'short_name' => null,
        'slug' => 'squat',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Standing',
        'short_name' => null,
        'slug' => 'standing',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Step-Up',
        'short_name' => null,
        'slug' => 'step-up',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Sternum',
        'short_name' => null,
        'slug' => 'sternum',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Stir the Pot',
        'short_name' => null,
        'slug' => 'stir-the-pot',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Straddle',
        'short_name' => null,
        'slug' => 'straddle',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Straight-Arm',
        'short_name' => null,
        'slug' => 'straight-arm',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Straight-Leg',
        'short_name' => null,
        'slug' => 'straight-leg',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Subscapularis',
        'short_name' => null,
        'slug' => 'subscapularis',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Sumo',
        'short_name' => null,
        'slug' => 'sumo',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Supinated',
        'short_name' => null,
        'slug' => 'supinated',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Supinating',
        'short_name' => null,
        'slug' => 'supinating',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Supine',
        'short_name' => null,
        'slug' => 'supine',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Supported',
        'short_name' => null,
        'slug' => 'supported',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Telemark',
        'short_name' => null,
        'slug' => 'telemark',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Telle',
        'short_name' => null,
        'slug' => 'telle',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'To Box',
        'short_name' => null,
        'slug' => 'to-box',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Toes Elevated',
        'short_name' => null,
        'slug' => 'toes-elevated',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Top Range',
        'short_name' => null,
        'slug' => 'top-range',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Triple Jumper',
        'short_name' => null,
        'slug' => 'triple-jumper',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Tuck',
        'short_name' => null,
        'slug' => 'tuck',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Unilateral',
        'short_name' => null,
        'slug' => 'unilateral',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Unrolling',
        'short_name' => null,
        'slug' => 'unrolling',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Unsupported',
        'short_name' => null,
        'slug' => 'unsupported',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Walk Out',
        'short_name' => null,
        'slug' => 'walk-out',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Walking',
        'short_name' => null,
        'slug' => 'walking',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Wide Grip',
        'short_name' => null,
        'slug' => 'wide-grip',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Wide Stance',
        'short_name' => null,
        'slug' => 'wide-stance',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Z',
        'short_name' => null,
        'slug' => 'z',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Zercher',
        'short_name' => null,
        'slug' => 'zercher',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Zombie',
        'short_name' => null,
        'slug' => 'zombie',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Zottman',
        'short_name' => null,
        'slug' => 'zottman',
        'sort_order' => 0,
    ],
    [
        'scope' => 'muscle_group',
        'name' => 'Back',
        'short_name' => null,
        'slug' => 'back',
        'sort_order' => 0,
    ],
    [
        'scope' => 'muscle_group',
        'name' => 'Biceps',
        'short_name' => null,
        'slug' => 'biceps',
        'sort_order' => 0,
    ],
    [
        'scope' => 'muscle_group',
        'name' => 'Calves',
        'short_name' => null,
        'slug' => 'calves',
        'sort_order' => 0,
    ],
    [
        'scope' => 'muscle_group',
        'name' => 'Chest',
        'short_name' => null,
        'slug' => 'chest',
        'sort_order' => 0,
    ],
    [
        'scope' => 'muscle_group',
        'name' => 'Core',
        'short_name' => null,
        'slug' => 'core',
        'sort_order' => 0,
    ],
    [
        'scope' => 'muscle_group',
        'name' => 'Glutes',
        'short_name' => null,
        'slug' => 'glutes',
        'sort_order' => 0,
    ],
    [
        'scope' => 'muscle_group',
        'name' => 'Hamstrings',
        'short_name' => null,
        'slug' => 'hamstrings',
        'sort_order' => 0,
    ],
    [
        'scope' => 'muscle_group',
        'name' => 'Quadriceps',
        'short_name' => null,
        'slug' => 'quadriceps',
        'sort_order' => 0,
    ],
    [
        'scope' => 'muscle_group',
        'name' => 'Shoulders',
        'short_name' => null,
        'slug' => 'shoulders',
        'sort_order' => 0,
    ],
    [
        'scope' => 'muscle_group',
        'name' => 'Triceps',
        'short_name' => null,
        'slug' => 'triceps',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_equipment',
        'name' => 'Long Gates',
        'short_name' => null,
        'slug' => 'long-gates',
        'sort_order' => 0,
    ],
    [
        'scope' => 'exercise_modifiers',
        'name' => 'Straight Setting',
        'short_name' => null,
        'slug' => 'straight-setting',
        'sort_order' => 0,
    ],
];
