<?php

return [
    [
        'id' => 2,
        'name' => 'Jump',
        'color' => 'amber',
        'sort' => 0,
        'config' => null,
    ],
    [
        'id' => 8,
        'name' => 'Ski',
        'color' => 'blue',
        'sort' => 0,
        'config' => null,
    ],
    [
        'id' => 9,
        'name' => 'Warm Up',
        'color' => 'indigo',
        'sort' => 0,
        'config' => null,
    ],
    [
        'id' => 10,
        'name' => 'Rehab',
        'color' => 'pink',
        'sort' => 0,
        'config' => null,
    ],
    [
        'id' => 11,
        'name' => 'Holiday',
        'color' => 'sky',
        'sort' => 0,
        'config' => null,
    ],
    [
        'id' => 12,
        'name' => 'Velocity',
        'color' => 'orange',
        'sort' => 0,
        'config' => null,
    ],
    [
        'id' => 13,
        'name' => 'Explosive Strenght',
        'color' => 'purple',
        'sort' => 0,
        'config' => null,
    ],
    [
        'id' => 14,
        'name' => 'Interval',
        'color' => 'lime',
        'sort' => 0,
        'config' => null,
    ],
    [
        'id' => 15,
        'name' => 'Rehab ACL',
        'color' => 'teal',
        'sort' => 0,
        'config' => null,
    ],
    [
        'id' => 1,
        'name' => 'Strength',
        'color' => 'red',
        'sort' => 1,
        'config' => null,
    ],
    [
        'id' => 3,
        'name' => 'Core',
        'color' => 'blue',
        'sort' => 2,
        'config' => null,
    ],
    [
        'id' => 4,
        'name' => 'Endurance',
        'color' => 'purple',
        'sort' => 3,
        'config' => null,
    ],
    [
        'id' => 5,
        'name' => 'Coordination',
        'color' => 'orange',
        'sort' => 4,
        'config' => null,
    ],
    [
        'id' => 6,
        'name' => 'Recovery',
        'color' => 'green',
        'sort' => 5,
        'config' => null,
    ],
    [
        'id' => 7,
        'name' => 'Miscellaneous',
        'color' => 'gray',
        'sort' => 6,
        'config' => null,
    ],
];
