<?php

return [
    [
        'id' => 74,
        'scope' => 'equipment',
        'name' => 'Barbell',
        'short_name' => null,
        'slug' => 'barbell',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 78,
        'scope' => 'equipment',
        'name' => 'Bodyweight',
        'short_name' => null,
        'slug' => 'bodyweight',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 77,
        'scope' => 'equipment',
        'name' => 'Cable Machine',
        'short_name' => null,
        'slug' => 'cable-machine',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 75,
        'scope' => 'equipment',
        'name' => 'Dumbbell',
        'short_name' => null,
        'slug' => 'dumbbell',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 76,
        'scope' => 'equipment',
        'name' => 'Kettlebell',
        'short_name' => null,
        'slug' => 'kettlebell',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 79,
        'scope' => 'equipment',
        'name' => 'Resistance Band',
        'short_name' => null,
        'slug' => 'resistance-band',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 324,
        'scope' => 'exercise_category',
        'name' => 'Coordination ',
        'short_name' => null,
        'slug' => 'coordination-1',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 359,
        'scope' => 'exercise_category',
        'name' => 'Interval',
        'short_name' => null,
        'slug' => 'interval-2',
        'parent_id' => null,
        'sort_order' => 1,
    ],
    [
        'id' => 331,
        'scope' => 'exercise_category',
        'name' => 'Recovery',
        'short_name' => null,
        'slug' => 'recovery',
        'parent_id' => null,
        'sort_order' => 2,
    ],
    [
        'id' => 347,
        'scope' => 'exercise_category',
        'name' => 'Rehab',
        'short_name' => null,
        'slug' => 'rehab',
        'parent_id' => null,
        'sort_order' => 3,
    ],
    [
        'id' => 323,
        'scope' => 'exercise_category',
        'name' => 'Strenght',
        'short_name' => null,
        'slug' => 'strenght-2',
        'parent_id' => null,
        'sort_order' => 4,
    ],
    [
        'id' => 313,
        'scope' => 'exercise_category',
        'name' => 'Velocity',
        'short_name' => null,
        'slug' => 'velocity',
        'parent_id' => null,
        'sort_order' => 5,
    ],
    [
        'id' => 297,
        'scope' => 'exercise_equipment',
        'name' => 'Ab Wheel',
        'short_name' => null,
        'slug' => 'ab-wheel',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 265,
        'scope' => 'exercise_equipment',
        'name' => 'Band',
        'short_name' => null,
        'slug' => 'band',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 244,
        'scope' => 'exercise_equipment',
        'name' => 'Bands',
        'short_name' => null,
        'slug' => 'bands',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 81,
        'scope' => 'exercise_equipment',
        'name' => 'BB',
        'short_name' => null,
        'slug' => 'bb',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 106,
        'scope' => 'exercise_equipment',
        'name' => 'Cable',
        'short_name' => null,
        'slug' => 'cable',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 101,
        'scope' => 'exercise_equipment',
        'name' => 'Cambered Bar',
        'short_name' => null,
        'slug' => 'cambered-bar',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 82,
        'scope' => 'exercise_equipment',
        'name' => 'DB',
        'short_name' => null,
        'slug' => 'db',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 144,
        'scope' => 'exercise_equipment',
        'name' => 'EZ Bar',
        'short_name' => null,
        'slug' => 'ez-bar',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 248,
        'scope' => 'exercise_equipment',
        'name' => 'Foam Roller',
        'short_name' => null,
        'slug' => 'foam-roller',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 261,
        'scope' => 'exercise_equipment',
        'name' => 'Glute Ham Developer',
        'short_name' => null,
        'slug' => 'glute-ham-developer',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 190,
        'scope' => 'exercise_equipment',
        'name' => 'Head Harness',
        'short_name' => null,
        'slug' => 'head-harness',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 328,
        'scope' => 'exercise_equipment',
        'name' => 'Hütchen',
        'short_name' => null,
        'slug' => 'hutchen',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 361,
        'scope' => 'exercise_equipment',
        'name' => 'Indoor Bike',
        'short_name' => null,
        'slug' => 'indoor-bike',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 250,
        'scope' => 'exercise_equipment',
        'name' => 'Leg Curl Machine',
        'short_name' => null,
        'slug' => 'leg-curl-machine',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 237,
        'scope' => 'exercise_equipment',
        'name' => 'Leg Press',
        'short_name' => null,
        'slug' => 'leg-press',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 312,
        'scope' => 'exercise_equipment',
        'name' => 'LH',
        'short_name' => null,
        'slug' => 'lh',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 273,
        'scope' => 'exercise_equipment',
        'name' => 'Machine',
        'short_name' => null,
        'slug' => 'machine',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 129,
        'scope' => 'exercise_equipment',
        'name' => 'Med Ball',
        'short_name' => null,
        'slug' => 'med-ball',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 366,
        'scope' => 'exercise_equipment',
        'name' => 'Outdoor Bike',
        'short_name' => null,
        'slug' => 'outdoor-bike',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 191,
        'scope' => 'exercise_equipment',
        'name' => 'Pinch Block',
        'short_name' => null,
        'slug' => 'pinch-block',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 194,
        'scope' => 'exercise_equipment',
        'name' => 'Pinch Card',
        'short_name' => null,
        'slug' => 'pinch-card',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 274,
        'scope' => 'exercise_equipment',
        'name' => 'Resistance Bands',
        'short_name' => null,
        'slug' => 'resistance-bands',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 130,
        'scope' => 'exercise_equipment',
        'name' => 'Rings',
        'short_name' => null,
        'slug' => 'rings',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 158,
        'scope' => 'exercise_equipment',
        'name' => 'Rope',
        'short_name' => null,
        'slug' => 'rope',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 197,
        'scope' => 'exercise_equipment',
        'name' => 'Safety Bar',
        'short_name' => null,
        'slug' => 'safety-bar',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 178,
        'scope' => 'exercise_equipment',
        'name' => 'Shoulder Horn',
        'short_name' => null,
        'slug' => 'shoulder-horn',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 308,
        'scope' => 'exercise_equipment',
        'name' => 'Skiboots',
        'short_name' => null,
        'slug' => 'skiboots',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 110,
        'scope' => 'exercise_equipment',
        'name' => 'Swiss Ball',
        'short_name' => null,
        'slug' => 'swiss-ball',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 147,
        'scope' => 'exercise_equipment',
        'name' => 'Thick Angled Bar',
        'short_name' => null,
        'slug' => 'thick-angled-bar',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 89,
        'scope' => 'exercise_equipment',
        'name' => 'Thick Bar',
        'short_name' => null,
        'slug' => 'thick-bar',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 145,
        'scope' => 'exercise_equipment',
        'name' => 'Thick EZ Bar',
        'short_name' => null,
        'slug' => 'thick-ez-bar',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 90,
        'scope' => 'exercise_equipment',
        'name' => 'Thick Multi-Angled Bar',
        'short_name' => null,
        'slug' => 'thick-multi-angled-bar',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 146,
        'scope' => 'exercise_equipment',
        'name' => 'Thick Parallel Bar',
        'short_name' => null,
        'slug' => 'thick-parallel-bar',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 195,
        'scope' => 'exercise_equipment',
        'name' => 'Thor\'s Hammer',
        'short_name' => null,
        'slug' => 'thors-hammer',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 203,
        'scope' => 'exercise_equipment',
        'name' => 'Trap Bar',
        'short_name' => null,
        'slug' => 'trap-bar',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 367,
        'scope' => 'exercise_equipment',
        'name' => 'treadmill',
        'short_name' => null,
        'slug' => 'treadmill',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 156,
        'scope' => 'exercise_equipment',
        'name' => 'Triceps Bar',
        'short_name' => null,
        'slug' => 'triceps-bar',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 185,
        'scope' => 'exercise_equipment',
        'name' => 'Weight Plate',
        'short_name' => null,
        'slug' => 'weight-plate',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 196,
        'scope' => 'exercise_equipment',
        'name' => 'Wrist Roller',
        'short_name' => null,
        'slug' => 'wrist-roller',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 260,
        'scope' => 'exercise_modifiers',
        'name' => '(2-1)',
        'short_name' => null,
        'slug' => '2-1',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 124,
        'scope' => 'exercise_modifiers',
        'name' => '15° Decline',
        'short_name' => null,
        'slug' => '15-decline',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 157,
        'scope' => 'exercise_modifiers',
        'name' => '15° Incline',
        'short_name' => null,
        'slug' => '15-incline',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 217,
        'scope' => 'exercise_modifiers',
        'name' => '2” Deficit',
        'short_name' => null,
        'slug' => '2-deficit',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 125,
        'scope' => 'exercise_modifiers',
        'name' => '25° Decline',
        'short_name' => null,
        'slug' => '25-decline',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 122,
        'scope' => 'exercise_modifiers',
        'name' => '3-Pause Eccentric',
        'short_name' => null,
        'slug' => '3-pause-eccentric',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 167,
        'scope' => 'exercise_modifiers',
        'name' => '35˚ Incline',
        'short_name' => null,
        'slug' => '350-incline',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 127,
        'scope' => 'exercise_modifiers',
        'name' => '35° Decline',
        'short_name' => null,
        'slug' => '35-decline',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 115,
        'scope' => 'exercise_modifiers',
        'name' => '35° Incline',
        'short_name' => null,
        'slug' => '35-incline',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 218,
        'scope' => 'exercise_modifiers',
        'name' => '4” Deficit',
        'short_name' => null,
        'slug' => '4-deficit',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 166,
        'scope' => 'exercise_modifiers',
        'name' => '45˚ Incline',
        'short_name' => null,
        'slug' => '450-incline',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 114,
        'scope' => 'exercise_modifiers',
        'name' => '45° Incline',
        'short_name' => null,
        'slug' => '45-incline',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 165,
        'scope' => 'exercise_modifiers',
        'name' => '55˚ Incline',
        'short_name' => null,
        'slug' => '550-incline',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 113,
        'scope' => 'exercise_modifiers',
        'name' => '55° Incline',
        'short_name' => null,
        'slug' => '55-incline',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 112,
        'scope' => 'exercise_modifiers',
        'name' => '65° Incline',
        'short_name' => null,
        'slug' => '65-incline',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 221,
        'scope' => 'exercise_modifiers',
        'name' => 'Above Knee',
        'short_name' => null,
        'slug' => 'above-knee',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 249,
        'scope' => 'exercise_modifiers',
        'name' => 'Accentuated Eccentric',
        'short_name' => null,
        'slug' => 'accentuated-eccentric',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 228,
        'scope' => 'exercise_modifiers',
        'name' => 'Alternated',
        'short_name' => null,
        'slug' => 'alternated',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 141,
        'scope' => 'exercise_modifiers',
        'name' => 'Arc',
        'short_name' => null,
        'slug' => 'arc',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 175,
        'scope' => 'exercise_modifiers',
        'name' => 'Arm in Front',
        'short_name' => null,
        'slug' => 'arm-in-front',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 177,
        'scope' => 'exercise_modifiers',
        'name' => 'Arm to Side',
        'short_name' => null,
        'slug' => 'arm-to-side',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 84,
        'scope' => 'exercise_modifiers',
        'name' => 'Arnold',
        'short_name' => null,
        'slug' => 'arnold',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 123,
        'scope' => 'exercise_modifiers',
        'name' => 'Assisted',
        'short_name' => null,
        'slug' => 'assisted',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 268,
        'scope' => 'exercise_modifiers',
        'name' => 'B Stance',
        'short_name' => null,
        'slug' => 'b-stance',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 270,
        'scope' => 'exercise_modifiers',
        'name' => 'Back',
        'short_name' => null,
        'slug' => 'back',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 358,
        'scope' => 'exercise_modifiers',
        'name' => 'Back Foot Elevated',
        'short_name' => null,
        'slug' => 'back-foot-elevated',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 275,
        'scope' => 'exercise_modifiers',
        'name' => 'Banded',
        'short_name' => null,
        'slug' => 'banded',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 88,
        'scope' => 'exercise_modifiers',
        'name' => 'Behind Neck',
        'short_name' => null,
        'slug' => 'behind-neck',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 109,
        'scope' => 'exercise_modifiers',
        'name' => 'Behind the Neck',
        'short_name' => null,
        'slug' => 'behind-the-neck',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 222,
        'scope' => 'exercise_modifiers',
        'name' => 'Below Knee',
        'short_name' => null,
        'slug' => 'below-knee',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 278,
        'scope' => 'exercise_modifiers',
        'name' => 'Bent-Knee',
        'short_name' => null,
        'slug' => 'bent-knee',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 140,
        'scope' => 'exercise_modifiers',
        'name' => 'Bent-Over',
        'short_name' => null,
        'slug' => 'bent-over',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 292,
        'scope' => 'exercise_modifiers',
        'name' => 'Bilateral',
        'short_name' => null,
        'slug' => 'bilateral',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 281,
        'scope' => 'exercise_modifiers',
        'name' => 'Birddog',
        'short_name' => null,
        'slug' => 'birddog',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 206,
        'scope' => 'exercise_modifiers',
        'name' => 'Bottom Range',
        'short_name' => null,
        'slug' => 'bottom-range',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 226,
        'scope' => 'exercise_modifiers',
        'name' => 'Bulgarian',
        'short_name' => null,
        'slug' => 'bulgarian',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 126,
        'scope' => 'exercise_modifiers',
        'name' => 'Califorina',
        'short_name' => null,
        'slug' => 'califorina',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 118,
        'scope' => 'exercise_modifiers',
        'name' => 'California',
        'short_name' => null,
        'slug' => 'california',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 86,
        'scope' => 'exercise_modifiers',
        'name' => 'Close Grip',
        'short_name' => null,
        'slug' => 'close-grip',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 180,
        'scope' => 'exercise_modifiers',
        'name' => 'Cobra',
        'short_name' => null,
        'slug' => 'cobra',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 161,
        'scope' => 'exercise_modifiers',
        'name' => 'Commerford',
        'short_name' => null,
        'slug' => 'commerford',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 225,
        'scope' => 'exercise_modifiers',
        'name' => 'Contralateral',
        'short_name' => null,
        'slug' => 'contralateral',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 286,
        'scope' => 'exercise_modifiers',
        'name' => 'Copenhagen',
        'short_name' => null,
        'slug' => 'copenhagen',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 179,
        'scope' => 'exercise_modifiers',
        'name' => 'Cuban Press',
        'short_name' => null,
        'slug' => 'cuban-press',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 201,
        'scope' => 'exercise_modifiers',
        'name' => 'Cyclist',
        'short_name' => null,
        'slug' => 'cyclist',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 289,
        'scope' => 'exercise_modifiers',
        'name' => 'Dips',
        'short_name' => null,
        'slug' => 'dips',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 253,
        'scope' => 'exercise_modifiers',
        'name' => 'Dorsiflexed',
        'short_name' => null,
        'slug' => 'dorsiflexed',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 231,
        'scope' => 'exercise_modifiers',
        'name' => 'Drop',
        'short_name' => null,
        'slug' => 'drop',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 280,
        'scope' => 'exercise_modifiers',
        'name' => 'Duchaine',
        'short_name' => null,
        'slug' => 'duchaine',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 246,
        'scope' => 'exercise_modifiers',
        'name' => 'Duck',
        'short_name' => null,
        'slug' => 'duck',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 121,
        'scope' => 'exercise_modifiers',
        'name' => 'Eccentric Only',
        'short_name' => null,
        'slug' => 'eccentric-only',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 176,
        'scope' => 'exercise_modifiers',
        'name' => 'Elbow on Knee',
        'short_name' => null,
        'slug' => 'elbow-on-knee',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 142,
        'scope' => 'exercise_modifiers',
        'name' => 'Elbow Out',
        'short_name' => null,
        'slug' => 'elbow-out',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 186,
        'scope' => 'exercise_modifiers',
        'name' => 'End Range',
        'short_name' => null,
        'slug' => 'end-range',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 187,
        'scope' => 'exercise_modifiers',
        'name' => 'External Rotation',
        'short_name' => null,
        'slug' => 'external-rotation',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 162,
        'scope' => 'exercise_modifiers',
        'name' => 'Face-Away',
        'short_name' => null,
        'slug' => 'face-away',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 182,
        'scope' => 'exercise_modifiers',
        'name' => 'Facing',
        'short_name' => null,
        'slug' => 'facing',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 290,
        'scope' => 'exercise_modifiers',
        'name' => 'Feet Down',
        'short_name' => null,
        'slug' => 'feet-down',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 241,
        'scope' => 'exercise_modifiers',
        'name' => 'Feet High',
        'short_name' => null,
        'slug' => 'feet-high',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 252,
        'scope' => 'exercise_modifiers',
        'name' => 'Feet In',
        'short_name' => null,
        'slug' => 'feet-in',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 245,
        'scope' => 'exercise_modifiers',
        'name' => 'Feet Low',
        'short_name' => null,
        'slug' => 'feet-low',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 255,
        'scope' => 'exercise_modifiers',
        'name' => 'Feet Neutral',
        'short_name' => null,
        'slug' => 'feet-neutral',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 131,
        'scope' => 'exercise_modifiers',
        'name' => 'Feet on Med Ball',
        'short_name' => null,
        'slug' => 'feet-on-med-ball',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 132,
        'scope' => 'exercise_modifiers',
        'name' => 'Feet on Swiss Ball',
        'short_name' => null,
        'slug' => 'feet-on-swiss-ball',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 256,
        'scope' => 'exercise_modifiers',
        'name' => 'Feet Out',
        'short_name' => null,
        'slug' => 'feet-out',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 291,
        'scope' => 'exercise_modifiers',
        'name' => 'Feet Up',
        'short_name' => null,
        'slug' => 'feet-up',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 116,
        'scope' => 'exercise_modifiers',
        'name' => 'Flat',
        'short_name' => null,
        'slug' => 'flat',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 119,
        'scope' => 'exercise_modifiers',
        'name' => 'Floor',
        'short_name' => null,
        'slug' => 'floor',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 242,
        'scope' => 'exercise_modifiers',
        'name' => 'Foot High',
        'short_name' => null,
        'slug' => 'foot-high',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 257,
        'scope' => 'exercise_modifiers',
        'name' => 'Foot In',
        'short_name' => null,
        'slug' => 'foot-in',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 258,
        'scope' => 'exercise_modifiers',
        'name' => 'Foot Neutral',
        'short_name' => null,
        'slug' => 'foot-neutral',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 259,
        'scope' => 'exercise_modifiers',
        'name' => 'Foot Out',
        'short_name' => null,
        'slug' => 'foot-out',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 234,
        'scope' => 'exercise_modifiers',
        'name' => 'Front',
        'short_name' => null,
        'slug' => 'front',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 356,
        'scope' => 'exercise_modifiers',
        'name' => 'Front Foot',
        'short_name' => null,
        'slug' => 'front-foot',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 223,
        'scope' => 'exercise_modifiers',
        'name' => 'Front Foot Elevated',
        'short_name' => null,
        'slug' => 'front-foot-elevated',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 357,
        'scope' => 'exercise_modifiers',
        'name' => 'Front Foot Flat On Floor',
        'short_name' => null,
        'slug' => 'front-foot-flat-on-floor',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 108,
        'scope' => 'exercise_modifiers',
        'name' => 'Front Rack',
        'short_name' => null,
        'slug' => 'front-rack',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 155,
        'scope' => 'exercise_modifiers',
        'name' => 'Full',
        'short_name' => null,
        'slug' => 'full',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 198,
        'scope' => 'exercise_modifiers',
        'name' => 'Goblet',
        'short_name' => null,
        'slug' => 'goblet',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 202,
        'scope' => 'exercise_modifiers',
        'name' => 'Hack',
        'short_name' => null,
        'slug' => 'hack',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 171,
        'scope' => 'exercise_modifiers',
        'name' => 'Half Kneeling',
        'short_name' => null,
        'slug' => 'half-kneeling-1',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 153,
        'scope' => 'exercise_modifiers',
        'name' => 'Half Lay',
        'short_name' => null,
        'slug' => 'half-lay',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 105,
        'scope' => 'exercise_modifiers',
        'name' => 'Half-Kneeling',
        'short_name' => null,
        'slug' => 'half-kneeling',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 330,
        'scope' => 'exercise_modifiers',
        'name' => 'Halle',
        'short_name' => null,
        'slug' => 'halle',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 238,
        'scope' => 'exercise_modifiers',
        'name' => 'Hamstring',
        'short_name' => null,
        'slug' => 'hamstring',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 247,
        'scope' => 'exercise_modifiers',
        'name' => 'Hamstring Walk',
        'short_name' => null,
        'slug' => 'hamstring-walk',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 309,
        'scope' => 'exercise_modifiers',
        'name' => 'Hand on',
        'short_name' => null,
        'slug' => 'hand-on',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 310,
        'scope' => 'exercise_modifiers',
        'name' => 'Hand on hip',
        'short_name' => null,
        'slug' => 'hand-on-hip',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 296,
        'scope' => 'exercise_modifiers',
        'name' => 'Hanging',
        'short_name' => null,
        'slug' => 'hanging',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 204,
        'scope' => 'exercise_modifiers',
        'name' => 'Hatfield',
        'short_name' => null,
        'slug' => 'hatfield',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 104,
        'scope' => 'exercise_modifiers',
        'name' => 'Heel Elevated',
        'short_name' => null,
        'slug' => 'heel-elevated',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 199,
        'scope' => 'exercise_modifiers',
        'name' => 'Heels Elevated',
        'short_name' => null,
        'slug' => 'heels-elevated',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 214,
        'scope' => 'exercise_modifiers',
        'name' => 'High Handles',
        'short_name' => null,
        'slug' => 'high-handles',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 148,
        'scope' => 'exercise_modifiers',
        'name' => 'High Pulley',
        'short_name' => null,
        'slug' => 'high-pulley',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 264,
        'scope' => 'exercise_modifiers',
        'name' => 'Hip Extension',
        'short_name' => null,
        'slug' => 'hip-extension',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 276,
        'scope' => 'exercise_modifiers',
        'name' => 'Horizontal',
        'short_name' => null,
        'slug' => 'horizontal',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 111,
        'scope' => 'exercise_modifiers',
        'name' => 'Incline',
        'short_name' => null,
        'slug' => 'incline',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 360,
        'scope' => 'exercise_modifiers',
        'name' => 'Indoor',
        'short_name' => null,
        'slug' => 'indoor',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 267,
        'scope' => 'exercise_modifiers',
        'name' => 'Inertia',
        'short_name' => null,
        'slug' => 'inertia',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 188,
        'scope' => 'exercise_modifiers',
        'name' => 'Internal Rotation',
        'short_name' => null,
        'slug' => 'internal-rotation',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 224,
        'scope' => 'exercise_modifiers',
        'name' => 'Ipsilateral',
        'short_name' => null,
        'slug' => 'ipsilateral',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 295,
        'scope' => 'exercise_modifiers',
        'name' => 'Janda',
        'short_name' => null,
        'slug' => 'janda',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 100,
        'scope' => 'exercise_modifiers',
        'name' => 'Javelin',
        'short_name' => null,
        'slug' => 'javelin',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 263,
        'scope' => 'exercise_modifiers',
        'name' => 'Knee Flexion',
        'short_name' => null,
        'slug' => 'knee-flexion',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 128,
        'scope' => 'exercise_modifiers',
        'name' => 'Kneeling',
        'short_name' => null,
        'slug' => 'kneeling',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 168,
        'scope' => 'exercise_modifiers',
        'name' => 'L-Style',
        'short_name' => null,
        'slug' => 'l-style',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 193,
        'scope' => 'exercise_modifiers',
        'name' => 'Large',
        'short_name' => null,
        'slug' => 'large',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 151,
        'scope' => 'exercise_modifiers',
        'name' => 'Lean 45°',
        'short_name' => null,
        'slug' => 'lean-45',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 135,
        'scope' => 'exercise_modifiers',
        'name' => 'Lean-Away',
        'short_name' => null,
        'slug' => 'lean-away',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 279,
        'scope' => 'exercise_modifiers',
        'name' => 'Leg Press',
        'short_name' => null,
        'slug' => 'leg-press',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 288,
        'scope' => 'exercise_modifiers',
        'name' => 'Long Lever',
        'short_name' => null,
        'slug' => 'long-lever',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 215,
        'scope' => 'exercise_modifiers',
        'name' => 'Low Handles',
        'short_name' => null,
        'slug' => 'low-handles',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 107,
        'scope' => 'exercise_modifiers',
        'name' => 'Low Pulley',
        'short_name' => null,
        'slug' => 'low-pulley',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 251,
        'scope' => 'exercise_modifiers',
        'name' => 'Lying',
        'short_name' => null,
        'slug' => 'lying',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 117,
        'scope' => 'exercise_modifiers',
        'name' => 'McGill',
        'short_name' => null,
        'slug' => 'mcgill',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 87,
        'scope' => 'exercise_modifiers',
        'name' => 'Medium Grip',
        'short_name' => null,
        'slug' => 'medium-grip',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 240,
        'scope' => 'exercise_modifiers',
        'name' => 'Medium Stance',
        'short_name' => null,
        'slug' => 'medium-stance',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 149,
        'scope' => 'exercise_modifiers',
        'name' => 'Mid Pulley',
        'short_name' => null,
        'slug' => 'mid-pulley',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 96,
        'scope' => 'exercise_modifiers',
        'name' => 'Mid Range',
        'short_name' => null,
        'slug' => 'mid-range',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 220,
        'scope' => 'exercise_modifiers',
        'name' => 'Mid Thigh',
        'short_name' => null,
        'slug' => 'mid-thigh',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 181,
        'scope' => 'exercise_modifiers',
        'name' => 'Muscle Snatch',
        'short_name' => null,
        'slug' => 'muscle-snatch',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 239,
        'scope' => 'exercise_modifiers',
        'name' => 'Narrow Stance',
        'short_name' => null,
        'slug' => 'narrow-stance',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 91,
        'scope' => 'exercise_modifiers',
        'name' => 'Neutral',
        'short_name' => null,
        'slug' => 'neutral',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 159,
        'scope' => 'exercise_modifiers',
        'name' => 'Offset',
        'short_name' => null,
        'slug' => 'offset',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 99,
        'scope' => 'exercise_modifiers',
        'name' => 'One-Arm',
        'short_name' => null,
        'slug' => 'one-arm',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 283,
        'scope' => 'exercise_modifiers',
        'name' => 'One-Leg',
        'short_name' => null,
        'slug' => 'one-leg',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 329,
        'scope' => 'exercise_modifiers',
        'name' => 'Outdoor',
        'short_name' => null,
        'slug' => 'outdoor',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 210,
        'scope' => 'exercise_modifiers',
        'name' => 'Overhead',
        'short_name' => null,
        'slug' => 'overhead',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 266,
        'scope' => 'exercise_modifiers',
        'name' => 'Partial',
        'short_name' => null,
        'slug' => 'partial',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 232,
        'scope' => 'exercise_modifiers',
        'name' => 'Petersen',
        'short_name' => null,
        'slug' => 'petersen',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 94,
        'scope' => 'exercise_modifiers',
        'name' => 'Pin Touch',
        'short_name' => null,
        'slug' => 'pin-touch',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 227,
        'scope' => 'exercise_modifiers',
        'name' => 'Pistol',
        'short_name' => null,
        'slug' => 'pistol',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 254,
        'scope' => 'exercise_modifiers',
        'name' => 'Plantarflexed',
        'short_name' => null,
        'slug' => 'plantarflexed',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 294,
        'scope' => 'exercise_modifiers',
        'name' => 'Pre-Stretch',
        'short_name' => null,
        'slug' => 'pre-stretch',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 120,
        'scope' => 'exercise_modifiers',
        'name' => 'Progression',
        'short_name' => null,
        'slug' => 'progression',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 138,
        'scope' => 'exercise_modifiers',
        'name' => 'Pronated',
        'short_name' => null,
        'slug' => 'pronated',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 164,
        'scope' => 'exercise_modifiers',
        'name' => 'Prone',
        'short_name' => null,
        'slug' => 'prone',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 200,
        'scope' => 'exercise_modifiers',
        'name' => 'Quad',
        'short_name' => null,
        'slug' => 'quad',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 219,
        'scope' => 'exercise_modifiers',
        'name' => 'Rack',
        'short_name' => null,
        'slug' => 'rack',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 262,
        'scope' => 'exercise_modifiers',
        'name' => 'Razor',
        'short_name' => null,
        'slug' => 'razor',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 80,
        'scope' => 'exercise_modifiers',
        'name' => 'Reverse',
        'short_name' => null,
        'slug' => 'reverse',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 272,
        'scope' => 'exercise_modifiers',
        'name' => 'Romanian',
        'short_name' => null,
        'slug' => 'romanian',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 213,
        'scope' => 'exercise_modifiers',
        'name' => 'Romanian Rhythm',
        'short_name' => null,
        'slug' => 'romanian-rhythm',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 184,
        'scope' => 'exercise_modifiers',
        'name' => 'Rope to Forehead',
        'short_name' => null,
        'slug' => 'rope-to-forehead',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 183,
        'scope' => 'exercise_modifiers',
        'name' => 'Rope to Neck',
        'short_name' => null,
        'slug' => 'rope-to-neck',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 282,
        'scope' => 'exercise_modifiers',
        'name' => 'Rotation',
        'short_name' => null,
        'slug' => 'rotation',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 235,
        'scope' => 'exercise_modifiers',
        'name' => 'Russian',
        'short_name' => null,
        'slug' => 'russian',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 85,
        'scope' => 'exercise_modifiers',
        'name' => 'Scott',
        'short_name' => null,
        'slug' => 'scott',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 83,
        'scope' => 'exercise_modifiers',
        'name' => 'Seated',
        'short_name' => null,
        'slug' => 'seated',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 93,
        'scope' => 'exercise_modifiers',
        'name' => 'Semi-pronated',
        'short_name' => null,
        'slug' => 'semi-pronated',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 134,
        'scope' => 'exercise_modifiers',
        'name' => 'Semi-Supinated',
        'short_name' => null,
        'slug' => 'semi-supinated',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 287,
        'scope' => 'exercise_modifiers',
        'name' => 'Short Lever',
        'short_name' => null,
        'slug' => 'short-lever',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 233,
        'scope' => 'exercise_modifiers',
        'name' => 'Side',
        'short_name' => null,
        'slug' => 'side',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 169,
        'scope' => 'exercise_modifiers',
        'name' => 'Side Lying',
        'short_name' => null,
        'slug' => 'side-lying',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 137,
        'scope' => 'exercise_modifiers',
        'name' => 'Side to Side',
        'short_name' => null,
        'slug' => 'side-to-side',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 174,
        'scope' => 'exercise_modifiers',
        'name' => 'Sideway',
        'short_name' => null,
        'slug' => 'sideway',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 271,
        'scope' => 'exercise_modifiers',
        'name' => 'Single-Leg Romanian',
        'short_name' => null,
        'slug' => 'single-leg-romanian',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 211,
        'scope' => 'exercise_modifiers',
        'name' => 'Sissy',
        'short_name' => null,
        'slug' => 'sissy',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 192,
        'scope' => 'exercise_modifiers',
        'name' => 'Small',
        'short_name' => null,
        'slug' => 'small',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 103,
        'scope' => 'exercise_modifiers',
        'name' => 'Sots',
        'short_name' => null,
        'slug' => 'sots',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 163,
        'scope' => 'exercise_modifiers',
        'name' => 'Spider',
        'short_name' => null,
        'slug' => 'spider',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 277,
        'scope' => 'exercise_modifiers',
        'name' => 'Squat',
        'short_name' => null,
        'slug' => 'squat',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 98,
        'scope' => 'exercise_modifiers',
        'name' => 'Standing',
        'short_name' => null,
        'slug' => 'standing',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 230,
        'scope' => 'exercise_modifiers',
        'name' => 'Step-Up',
        'short_name' => null,
        'slug' => 'step-up',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 136,
        'scope' => 'exercise_modifiers',
        'name' => 'Sternum',
        'short_name' => null,
        'slug' => 'sternum',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 284,
        'scope' => 'exercise_modifiers',
        'name' => 'Stir the Pot',
        'short_name' => null,
        'slug' => 'stir-the-pot',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 154,
        'scope' => 'exercise_modifiers',
        'name' => 'Straddle',
        'short_name' => null,
        'slug' => 'straddle',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 173,
        'scope' => 'exercise_modifiers',
        'name' => 'Straight-Arm',
        'short_name' => null,
        'slug' => 'straight-arm',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 293,
        'scope' => 'exercise_modifiers',
        'name' => 'Straight-Leg',
        'short_name' => null,
        'slug' => 'straight-leg',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 139,
        'scope' => 'exercise_modifiers',
        'name' => 'Subscapularis',
        'short_name' => null,
        'slug' => 'subscapularis',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 216,
        'scope' => 'exercise_modifiers',
        'name' => 'Sumo',
        'short_name' => null,
        'slug' => 'sumo',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 143,
        'scope' => 'exercise_modifiers',
        'name' => 'Supinated',
        'short_name' => null,
        'slug' => 'supinated',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 133,
        'scope' => 'exercise_modifiers',
        'name' => 'Supinating',
        'short_name' => null,
        'slug' => 'supinating',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 189,
        'scope' => 'exercise_modifiers',
        'name' => 'Supine',
        'short_name' => null,
        'slug' => 'supine',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 170,
        'scope' => 'exercise_modifiers',
        'name' => 'Supported',
        'short_name' => null,
        'slug' => 'supported',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 212,
        'scope' => 'exercise_modifiers',
        'name' => 'Telemark',
        'short_name' => null,
        'slug' => 'telemark',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 150,
        'scope' => 'exercise_modifiers',
        'name' => 'Telle',
        'short_name' => null,
        'slug' => 'telle',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 205,
        'scope' => 'exercise_modifiers',
        'name' => 'To Box',
        'short_name' => null,
        'slug' => 'to-box',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 269,
        'scope' => 'exercise_modifiers',
        'name' => 'Toes Elevated',
        'short_name' => null,
        'slug' => 'toes-elevated',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 95,
        'scope' => 'exercise_modifiers',
        'name' => 'Top Range',
        'short_name' => null,
        'slug' => 'top-range',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 236,
        'scope' => 'exercise_modifiers',
        'name' => 'Triple Jumper',
        'short_name' => null,
        'slug' => 'triple-jumper',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 152,
        'scope' => 'exercise_modifiers',
        'name' => 'Tuck',
        'short_name' => null,
        'slug' => 'tuck',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 243,
        'scope' => 'exercise_modifiers',
        'name' => 'Unilateral',
        'short_name' => null,
        'slug' => 'unilateral',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 172,
        'scope' => 'exercise_modifiers',
        'name' => 'Unrolling',
        'short_name' => null,
        'slug' => 'unrolling',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 97,
        'scope' => 'exercise_modifiers',
        'name' => 'Unsupported',
        'short_name' => null,
        'slug' => 'unsupported',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 285,
        'scope' => 'exercise_modifiers',
        'name' => 'Walk Out',
        'short_name' => null,
        'slug' => 'walk-out',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 229,
        'scope' => 'exercise_modifiers',
        'name' => 'Walking',
        'short_name' => null,
        'slug' => 'walking',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 92,
        'scope' => 'exercise_modifiers',
        'name' => 'Wide Grip',
        'short_name' => null,
        'slug' => 'wide-grip',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 207,
        'scope' => 'exercise_modifiers',
        'name' => 'Wide Stance',
        'short_name' => null,
        'slug' => 'wide-stance',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 102,
        'scope' => 'exercise_modifiers',
        'name' => 'Z',
        'short_name' => null,
        'slug' => 'z',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 208,
        'scope' => 'exercise_modifiers',
        'name' => 'Zercher',
        'short_name' => null,
        'slug' => 'zercher',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 209,
        'scope' => 'exercise_modifiers',
        'name' => 'Zombie',
        'short_name' => null,
        'slug' => 'zombie',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 160,
        'scope' => 'exercise_modifiers',
        'name' => 'Zottman',
        'short_name' => null,
        'slug' => 'zottman',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 65,
        'scope' => 'muscle_group',
        'name' => 'Back',
        'short_name' => null,
        'slug' => 'back',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 70,
        'scope' => 'muscle_group',
        'name' => 'Biceps',
        'short_name' => null,
        'slug' => 'biceps',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 73,
        'scope' => 'muscle_group',
        'name' => 'Calves',
        'short_name' => null,
        'slug' => 'calves',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 64,
        'scope' => 'muscle_group',
        'name' => 'Chest',
        'short_name' => null,
        'slug' => 'chest',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 72,
        'scope' => 'muscle_group',
        'name' => 'Core',
        'short_name' => null,
        'slug' => 'core',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 69,
        'scope' => 'muscle_group',
        'name' => 'Glutes',
        'short_name' => null,
        'slug' => 'glutes',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 68,
        'scope' => 'muscle_group',
        'name' => 'Hamstrings',
        'short_name' => null,
        'slug' => 'hamstrings',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 67,
        'scope' => 'muscle_group',
        'name' => 'Quadriceps',
        'short_name' => null,
        'slug' => 'quadriceps',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 66,
        'scope' => 'muscle_group',
        'name' => 'Shoulders',
        'short_name' => null,
        'slug' => 'shoulders',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 71,
        'scope' => 'muscle_group',
        'name' => 'Triceps',
        'short_name' => null,
        'slug' => 'triceps',
        'parent_id' => null,
        'sort_order' => 0,
    ],
    [
        'id' => 336,
        'scope' => 'exercise_category',
        'name' => '90/90',
        'short_name' => null,
        'slug' => '9090',
        'parent_id' => 335,
        'sort_order' => 0,
    ],
    [
        'id' => 346,
        'scope' => 'exercise_category',
        'name' => 'Absolute Strenght',
        'short_name' => null,
        'slug' => 'absolute-strenght',
        'parent_id' => 323,
        'sort_order' => 0,
    ],
    [
        'id' => 315,
        'scope' => 'exercise_category',
        'name' => 'Acceleration ',
        'short_name' => null,
        'slug' => 'acceleration',
        'parent_id' => 313,
        'sort_order' => 0,
    ],
    [
        'id' => 349,
        'scope' => 'exercise_category',
        'name' => 'Achilles',
        'short_name' => null,
        'slug' => 'achilles',
        'parent_id' => 347,
        'sort_order' => 0,
    ],
    [
        'id' => 353,
        'scope' => 'exercise_category',
        'name' => 'Acute Phase 0-2 Weeks',
        'short_name' => null,
        'slug' => 'acute-phase-0-2-weeks',
        'parent_id' => 348,
        'sort_order' => 0,
    ],
    [
        'id' => 351,
        'scope' => 'exercise_category',
        'name' => 'Acute Protection Phase 0-2 Weeks',
        'short_name' => null,
        'slug' => 'acute-protection-phase-0-2-weeks',
        'parent_id' => 349,
        'sort_order' => 0,
    ],
    [
        'id' => 325,
        'scope' => 'exercise_category',
        'name' => 'Fliegend sprint',
        'short_name' => null,
        'slug' => 'fliegend-sprint',
        'parent_id' => 315,
        'sort_order' => 0,
    ],
    [
        'id' => 332,
        'scope' => 'exercise_category',
        'name' => 'Foam Rolling ',
        'short_name' => null,
        'slug' => 'foam-rolling',
        'parent_id' => 331,
        'sort_order' => 0,
    ],
    [
        'id' => 327,
        'scope' => 'exercise_category',
        'name' => 'Frontal',
        'short_name' => null,
        'slug' => 'frontal',
        'parent_id' => 316,
        'sort_order' => 0,
    ],
    [
        'id' => 335,
        'scope' => 'exercise_category',
        'name' => 'Hipmobility',
        'short_name' => null,
        'slug' => 'hipmobility',
        'parent_id' => 333,
        'sort_order' => 0,
    ],
    [
        'id' => 364,
        'scope' => 'exercise_category',
        'name' => 'Interval Bike Extensiv Indoor ',
        'short_name' => null,
        'slug' => 'interval-bike-extensiv-indoor',
        'parent_id' => 359,
        'sort_order' => 0,
    ],
    [
        'id' => 334,
        'scope' => 'exercise_category',
        'name' => 'Legs',
        'short_name' => null,
        'slug' => 'legs',
        'parent_id' => 332,
        'sort_order' => 0,
    ],
    [
        'id' => 348,
        'scope' => 'exercise_category',
        'name' => 'ACL',
        'short_name' => null,
        'slug' => 'acl',
        'parent_id' => 347,
        'sort_order' => 1,
    ],
    [
        'id' => 317,
        'scope' => 'exercise_category',
        'name' => 'Agillity',
        'short_name' => null,
        'slug' => 'agillity',
        'parent_id' => 313,
        'sort_order' => 1,
    ],
    [
        'id' => 354,
        'scope' => 'exercise_category',
        'name' => 'Early Loading Phase 2-6 Weeks',
        'short_name' => null,
        'slug' => 'early-loading-phase-2-6-weeks',
        'parent_id' => 349,
        'sort_order' => 1,
    ],
    [
        'id' => 342,
        'scope' => 'exercise_category',
        'name' => 'Endurance Strenght',
        'short_name' => null,
        'slug' => 'endurance-strenght',
        'parent_id' => 323,
        'sort_order' => 1,
    ],
    [
        'id' => 363,
        'scope' => 'exercise_category',
        'name' => 'Interval Bike Extensiv Outdoor',
        'short_name' => null,
        'slug' => 'interval-bike-extensiv-outdoor',
        'parent_id' => 359,
        'sort_order' => 1,
    ],
    [
        'id' => 326,
        'scope' => 'exercise_category',
        'name' => 'Lateral',
        'short_name' => null,
        'slug' => 'lateral',
        'parent_id' => 316,
        'sort_order' => 1,
    ],
    [
        'id' => 333,
        'scope' => 'exercise_category',
        'name' => 'Mobility',
        'short_name' => null,
        'slug' => 'mobility',
        'parent_id' => 331,
        'sort_order' => 1,
    ],
    [
        'id' => 355,
        'scope' => 'exercise_category',
        'name' => 'Phase 2 Early Strenght 2-6 Week',
        'short_name' => null,
        'slug' => 'phase-2-early-strenght-2-6-week',
        'parent_id' => 348,
        'sort_order' => 1,
    ],
    [
        'id' => 337,
        'scope' => 'exercise_category',
        'name' => 'Standing Hip Rotation',
        'short_name' => null,
        'slug' => 'standing-hip-rotation',
        'parent_id' => 335,
        'sort_order' => 1,
    ],
    [
        'id' => 316,
        'scope' => 'exercise_category',
        'name' => 'Change of direction ',
        'short_name' => null,
        'slug' => 'change-of-direction',
        'parent_id' => 313,
        'sort_order' => 2,
    ],
    [
        'id' => 340,
        'scope' => 'exercise_category',
        'name' => 'Explosive Strenght',
        'short_name' => null,
        'slug' => 'explosive-strenght',
        'parent_id' => 323,
        'sort_order' => 2,
    ],
    [
        'id' => 365,
        'scope' => 'exercise_category',
        'name' => 'Interval Jogging Extensiv Indoor',
        'short_name' => null,
        'slug' => 'interval-jogging-extensiv-indoor',
        'parent_id' => 359,
        'sort_order' => 2,
    ],
    [
        'id' => 350,
        'scope' => 'exercise_category',
        'name' => 'Meniscus',
        'short_name' => null,
        'slug' => 'meniscus',
        'parent_id' => 347,
        'sort_order' => 2,
    ],
    [
        'id' => 319,
        'scope' => 'exercise_category',
        'name' => 'Frequence',
        'short_name' => null,
        'slug' => 'frequence',
        'parent_id' => 313,
        'sort_order' => 3,
    ],
    [
        'id' => 338,
        'scope' => 'exercise_category',
        'name' => 'Hypertrophie',
        'short_name' => null,
        'slug' => 'hypertrophie',
        'parent_id' => 323,
        'sort_order' => 3,
    ],
    [
        'id' => 362,
        'scope' => 'exercise_category',
        'name' => 'Interval Jogging Extensiv Outdoor',
        'short_name' => null,
        'slug' => 'interval-jogging-extensiv-outdoor',
        'parent_id' => 359,
        'sort_order' => 3,
    ],
    [
        'id' => 344,
        'scope' => 'exercise_category',
        'name' => 'Isometric Strenght',
        'short_name' => null,
        'slug' => 'isometric-strenght',
        'parent_id' => 323,
        'sort_order' => 4,
    ],
    [
        'id' => 321,
        'scope' => 'exercise_category',
        'name' => 'Max velocity',
        'short_name' => null,
        'slug' => 'max-velocity',
        'parent_id' => 313,
        'sort_order' => 4,
    ],
    [
        'id' => 339,
        'scope' => 'exercise_category',
        'name' => 'Maximum Strenght',
        'short_name' => null,
        'slug' => 'maximum-strenght',
        'parent_id' => 323,
        'sort_order' => 5,
    ],
    [
        'id' => 318,
        'scope' => 'exercise_category',
        'name' => 'Plyometrics',
        'short_name' => null,
        'slug' => 'plyometrics',
        'parent_id' => 313,
        'sort_order' => 5,
    ],
    [
        'id' => 343,
        'scope' => 'exercise_category',
        'name' => 'Reactive Strenght',
        'short_name' => null,
        'slug' => 'reactive-strenght',
        'parent_id' => 323,
        'sort_order' => 6,
    ],
    [
        'id' => 322,
        'scope' => 'exercise_category',
        'name' => 'Repeated Sprint Ability',
        'short_name' => null,
        'slug' => 'repeated-sprint-ability',
        'parent_id' => 313,
        'sort_order' => 6,
    ],
    [
        'id' => 345,
        'scope' => 'exercise_category',
        'name' => 'Relative Strenght',
        'short_name' => null,
        'slug' => 'relative-strenght',
        'parent_id' => 323,
        'sort_order' => 7,
    ],
    [
        'id' => 320,
        'scope' => 'exercise_category',
        'name' => 'Speed endurance ',
        'short_name' => null,
        'slug' => 'speed-endurance',
        'parent_id' => 313,
        'sort_order' => 7,
    ],
    [
        'id' => 341,
        'scope' => 'exercise_category',
        'name' => 'Speed Strenght',
        'short_name' => null,
        'slug' => 'speed-strenght',
        'parent_id' => 323,
        'sort_order' => 8,
    ],
];
