<?php

return [
    'equipment' => [
        'name_rules' => [
            'Med Ball' => 'Med Ball',
            'Swiss Ball' => 'Swiss Ball',
            'Pulldown' => 'Cable',
            'Low Pulley' => 'Cable',
            'Mid Pulley' => 'Cable',
            'High Pulley' => 'Cable',
            'Ab Roll-Out' => 'Ab Wheel',
            'Row - Seated' => 'Cable',
            'Deadlift' => 'BB',
            'Wrist Roller' => 'Wrist Roller',
            'Pinch Block' => 'Pinch Block',
            'Pinch Card' => 'Pinch Card',
            'Squat' => 'BB',
            'Front Squat' => 'BB',
            'Leg Press' => 'Leg Press',
            'Leg Curl' => 'Leg Curl Machine',
            'Banded' => 'Resistance Bands',
        ],
        'exercises' => [
            'Ab Rotation - Seated' => 'Med Ball',
            'Overhead Press' => 'BB',
            'Horizontal Abduction - End Range - External Rotation' => 'Weight Plate',
            'Horizontal Abduction - End Range - Internal Rotation' => 'Weight Plate',
            'Glute Ham Raise - Razor' => 'Glute Ham Developer',
            'Glute Ham Raise - Knee Flexion' => 'Glute Ham Developer',
            'Glute Ham Raise - Knee Flexion - Accentuated Eccentric' => 'Glute Ham Developer',
            'Glute Ham Raise - Hip Extension' => 'Glute Ham Developer',
            'Glute Ham Raise - Hip Extension - Accentuated Eccentric' => 'Glute Ham Developer',
            'Back Extension - Incline' => 'Glute Ham Developer',
            'Back Extension - Incline - Unilateral' => 'Glute Ham Developer',
            'Back Extension - Horizontal' => 'Glute Ham Developer',
            'Back Extension - Horizontal - Unilateral' => 'Glute Ham Developer',
            'Reverse Hyper' => 'Glute Ham Developer',
            'Reverse Hyper - Unilateral' => 'Glute Ham Developer',
        ],
    ],
    'bodyweight' => [
        'name_rules' => [
            'Push-Up',
            'Pull-Up',
            'Chin-Up',
            'Dip',
            'Front Lever',
            'Nordic Curl',
            'Pistol',
            'Glute Bridge',
            'Low Ab Drill',
            'Crunch',
            'Hip Raise',
            'Sit-Up',
            'Garhammer Raise',
            'Leg Raise',
            'King Deadlift',
            'Plank',
            'Dragon Flag',
            'Sissy',

        ],
        'exercises' => [
            'Anterior Tibialis Raise - Standing',
            'Anterior Tibialis Raise - Standing - Bent-Knee',
            'Renegade Row',
            'Anterior Tibialis Raise - Standing',
            'Anterior Tibialis Raise - Standing - Bent-Knee',
            'Hip Extension - Supine',
            'Hip Extension - Supine - Unilateral',
            'Knee Flexion - Hamstring Walk',
            'Squat - Hack',
            'Step-Up - Heel Elevated',
            'Step-Up - Petersen',
            'Step-Up - Side',
            'Step-Up - Front',
            'Step-Up - Front - Alternated',
            'Step-Up - Russian',
            'Step-Up - Russian - Alternated',
            'Step-Up - Triple Jumper',
        ],
    ],
];
